export const SkillId = {
  EnTextTidalWave: "TidalWave",
  UnknownSkillWaterWave: "WaterWave",
  HydroJet: "AquaJet",
  AquaGun: "WaterGun",
  BubbleBlast: "BubbleShot",
  AcidRain: "AcidRain",
  AquaBurst: "WaterBall",
  SurfingSlam: "Unique_BluePlatypus_Toboggan",
  HydroLaser: "HydroPump",
  Intimidate: "Intimidate",
  Punch: "Human_Punch",
  AirCannon: "AirCanon",
  ChickenRush: "Unique_ChickenPal_ChickenPeck",
  PowerShot: "PowerShot",
  RolyPoly: "Unique_SheepBall_Roll",
  PunchFlurry: "Unique_PinkCat_CatPunch",
  FluffyTackle: "Unique_Alpaca_Tackle",
  FierceFang: "Unique_Garm_Bite",
  AntlerUppercut: "Unique_Deer_PushupHorn",
  RecklessCharge: "Unique_Boar_Tackle",
  GaleClaw: "Unique_Eagle_GlidingNail",
  CatPress: "Unique_NaughtyCat_CatPress",
  EnTextThrow: "Throw",
  TornadoAttack: "Unique_HawkBird_Storm",
  PowerBomb: "PowerBall",
  MuscleSlam: "Unique_SakuraSaurus_SideTackle",
  GroundPound: "Unique_Gorilla_GroundPunch",
  CloudTempest: "Unique_FengyunDeeper_CloudTempest",
  EnTextScratch: "Scratch",
  UnknownSkillWorkAttack: "WorkAttack",
  KinglySlam: "Unique_KingAlpaca_BodyPress",
  SpearThrust: "Unique_SaintCentaur_OneSpearRushes",
  PalBlast: "HyperBeam",
  Implode: "SelfDestruct",
  BeeQuiet: "SelfDestruct_Bee",
  MegatonImplode: "SelfExplosion",
  WindCutter: "WindCutter",
  SeedMachineGun: "SeedMachinegun",
  BotanicalSmash: "Unique_FlowerDinosaur_Whip",
  Multicutter: "SpecialCutter",
  SeedMine: "SeedMine",
  FocusShot: "Unique_RobinHood_BowSnipe",
  SpinningStaff: "Unique_QueenBee_SpinLance",
  GrassTornado: "GrassTornado",
  CrushingPunch: "Unique_GrassPanda_MusclePunch",
  SpineVine: "RootAttack",
  SolarBlast: "SolarBeam",
  EnTextSnowStorm: "SnowStorm",
  IceMissile: "EnergyShot",
  IceMissileIceMissile: "IceMissile",
  IcicleCutter: "IceBlade",
  FreezingCharge: "Unique_IceDeer_IceHorn",
  Iceberg: "BlizzardLance",
  EmperorSlide: "Unique_CaptainPenguin_BodySlide",
  CrystalBreath: "FrostBreath",
  FrostBurst: "Unique_VolcanicMonster_Ice_IceAttack",
  CrystalWing: "Unique_IceHorse_IceBladeAttack",
  BlizzardSpike: "IcicleThrow",
  IgnisBlast: "FireBlast",
  SpiritFire: "FireSeed",
  BlazingHorn: "Unique_FlameBuffalo_FlameHorn",
  FlareArrow: "FlareArrow",
  Iaigiri: "Unique_Ronin_Iai",
  IgnisBreath: "Flamethrower",
  HellfireClaw: "Unique_Baphomet_SwallowKite",
  DaringFlames: "Unique_AmaterasuWolf_FireCharge",
  FlareStorm: "FlareTornado",
  IgnisCharge: "Unique_FireKirin_Tackle",
  VolcanicBurst: "Unique_VolcanicMonster_MagmaAttack",
  IgnisRage: "Inferno",
  PhoenixFlare: "Unique_Horus_FlareBird",
  FireBall: "FireBall",
  CrossLightning: "CrossThunder",
  ThunderRain: "ThunderRain",
  SparkBlast: "SpreadPulse",
  UnknownSkillFunnelRaijinDaughter: "Funnel_RaijinDaughter",
  Shockwave: "ElecWave",
  ElectricBall: "ThunderBall",
  PlasmaFunnel: "ThunderFunnel",
  LockOnLaser: "LockonLaser",
  LightningClaw: "Unique_ElecPanda_ElecScratch",
  LightningStreak: "LineThunder",
  BlastPunch: "Unique_GrassPanda_Electric_ElectricPunch",
  TriLightning: "ThreeThunder",
  LightningGale: "Unique_Kirin_LightningTackle",
  Kerauno: "Unique_ThunderDragonMan_ThunderSwordAttack",
  LightningStrike: "LightningStrike",
  LightningBolt: "Thunderbolt",
  BogBlast: "MudShot",
  StoneBlast: "StoneShotgun",
  ShellSpin: "Unique_DrillGame_ShellAttack",
  StoneCannon: "ThrowRock",
  GigaHorn: "Unique_HerculesBeetle_BeetleTackle",
  SandTornado: "SandTornado",
  SpinningRoundhouse: "Unique_Anubis_LowRoundKick",
  EarthImpact: "Unique_Grassmammoth_Earthquake",
  ForcefulCharge: "Unique_Anubis_Tackle",
  GroundSmash: "Unique_Anubis_GroundPunch",
  RockLance: "RockLance",
  DragonCannon: "DragonCanon",
  DragonBurst: "DragonWave",
  DragonBreath: "DragonBreath",
  MysticWhirlwind: "Unique_FairyDragon_FairyTornado",
  BeamComet: "Unique_JetDragon_JumpBeam",
  DragonMeteor: "DragonMeteor",
  PoisonFog: "PoisonFog",
  UnknownSkillFunnelDreamDemon: "Funnel_DreamDemon",
  PoisonBlast: "PoisonShot",
  DarkBall: "DarkBall",
  ShadowBurst: "DarkWave",
  PhantomPeck: "Unique_DarkCrow_TelePoke",
  JumpingClaw: "Unique_Werewolf_Scratch",
  SpiritFlame: "GhostFlame",
  DarkCharge: "Unique_FireKirin_Dark_DarkTossin",
  NightmareBall: "ShadowBall",
  PsychoGravity: "Psychokinesis",
  TwinSpears: "Unique_BlackCentaur_TwoSpearRushes",
  DarkLaser: "DarkLaser",
  DivineDisaster: "Unique_BlackGriffon_TackleLaser",
  DarkWhisp: "DarkLegion",
  RocketSlam: "Unique_WeaselDragon_FlyingTackle",
  Rockburst: "Tremor",
  DiamondRain: "DiamondFall",
  BeamSlicer: "BeamSlicer",
  NightmareBloom: "Unique_NightLady_WarpBeam",
  FlameWaltz: "Unique_NightLady_FlameNightmare",
  CometStrike: "Commet",
  UmbralSurge: "DarkPulse",
  DarkCannon: "DarkCanon",
  DarkArrow: "DarkArrow",
  Apocalypse: "Apocalypse",
  NightmareRay: "Unique_NightLady_WarpBeam_Straight",
  JumpingStinger: "Unique_DarkScorpion_Pierce",
  StarMine: "StarMine",
  EarthDash: "Unique_FeatherOstrich_Tossin",
  CircleVine: "RootLance",
  Polykeraunos: "Unique_ThunderDragonMan_NumerousSwordAttack",
  MagnaCrush: "Unique_KingBahamut_AirCrash",
  Splash: "LineGeyser",
  ChargeCannon: "ChargeCanon",
  BrawnImpact: "Unique_KingBahamut_ArmSmash",
  GroundCutter: "Unique_WingGolem_RoundCutter",
  BlastCannon: "BlastCanon",
  CometBarrage: "ThreeCommet",
  Meteorain: "CommetRain",
  VolcanicRain: "Eruption",
  HeavyThunderTank: "Unique_ElecPanda_GatlingAttack",
  BountifulProtection: "Unique_LilyQueen_LilyHealing",
  HolyBurst: "HolyBlast",
  EvilSlash: "Unique_DarkAlien_JumpScractch",
  MoonlightBeam: "Unique_MoonQueen_MoonBeam",
  FlameWall: "FlameWall",
  AirBlade: "AirBlade",
  SeigetsuBlade: "Unique_MoonQueen_MoonBlade",
  WholeheartedStance: "Unique_SifuDog_Counter",
  CurtainSplash: "WallSplash",
  TriSpark: "TriSpark",
  Thunderstorm: "ThunderStorm",
  UpperSmash: "Unique_ScorpionMan_Uppercut",
  FlameFunnel: "FlameFunnel",
  SandTwister: "SandTwister",
  AllRangeThunder: "RangeThunder",
  ThunderRail: "Railbolt",
  LethalLaser: "ShokeiLaser",
  PoisonShower: "BubbleShower",
  UnknownSkillWaterBalloon: "WaterBalloon",
  IcicleBullet: "IciclePierce",
  DoubleBlizzardSpike: "DoubleIcicleThrow",
  AbsoluteFrost: "IceAge",
  RaidCutter: "RaidCutter",
  WindEdge: "WindEdge",
  FlareTwister: "FlareTwister",
  RagingFlameWave: "Unique_Horus_PerfectStorm",
  DivineDisasterII: "Unique_BlackGriffon_TackleLaser2",
  SeigetsuFlash: "Unique_MoonQueen_IceMoonBlade",
  IcicleLine: "IcicleLine",
  VolcanicFang: "Unique_Manticore_InfernoStrike",
  LightningDive: "Unique_ThunderBird_ThunderStorm",
  WindBarrier: "Unique_LilyQueen_WindBarrier",
  FirefistBreathstorm: "Unique_BlackMetalDragon_FirePunch",
  LeapingRoundhouse: "Unique_GrassRabbitMan_GrassRoundKick",
  SnowBowling: "Unique_Yeti_SnowBall",
  SlitherSlam: "Unique_Umihebi_WindingTackle",
  NeedleSpear: "Unique_SoldierBee_NeedleLance",
  RushBeak: "Unique_RedArmorBird_TriplePeck",
  BeckonLightning: "Unique_ThunderDog_InazumaShorai",
  SpiritDash: "Unique_GhostBeast_Tossin",
  FlameBreath: "Unique_BirdDragon_FireBreath",
  BlizzardClaw: "Unique_WhiteTiger_IceScratch",
  SatelliteBit: "Unique_DarkMechaDragon_SetFunnel",
  OmegaLaser: "Unique_DarkMechaDragon_FunnelLaser",
  AstralRay: "Unique_DarkMechaDragon_ConvergentBeam",
  BeamSlash: "Unique_DarkMechaDragon_BeamSlash",
  CosmicMeteor: "Unique_DarkMechaDragon_WarpComet",
  TempestBlizzard: "Unique_BirdDragon_Ice_IceBreath",
  MagmaSerpent: "Unique_Umihebi_Fire_FireWindingTackle",
  PredatorSurge: "PredatorWave",
  PredatorBlast: "PredatorBeam",
  PredatorMark: "PredatorLockon",
  StoneClaw: "Unique_WhiteTiger_Ground_IronScratch",
  ThunderTempest: "Unique_FengyunDeeper_Electric_ThunderTempest",
  SnowClaw: "Unique_Werewolf_Ice_SnowScratch",
  PhoenixTide: "Unique_Horus_Water_AquaStorm",
  DaringShadowstorm: "Unique_AmaterasuWolf_Dark_DarkCharge",
  RockyImpact: "RockBeat",
  LawnBowling: "Unique_Yeti_Grass_GrassBall",
  GlacialImpact: "Unique_SnowTigerBeastman_SnowImpact",
  WebstrikeImpact: "Unique_PurpleSpider_SpiderRaid",
  FrostTalon: "Unique_SnowTigerBeastman_TrampleSlash",
  SoulDrain: "Unique_MysteryMask_LifeSteal",
  GrudgeBarrage: "Unique_GrimGirl_BrutalMachete",
  AegisCharge: "Unique_WhiteShieldDragon_ShieldTackle",
  BoltBlink: "Unique_BlueThunderHorse_FlashDash",
  HolyNova: "Unique_WhiteDeer_HolyPillar",
  LethalStep: "Unique_NightBlueHorse_DeathStep",
  CrashDash: "Unique_GoldenHorse_StoneDash",
  UnknownSkillFunnelRaijinDaughterWater: "Funnel_RaijinDaughter_Water",
  PlasmaDash: "PARTNERSKILL_BlueThunderHorse",
  GeyserGush: "SeaGush",
  AquaSurge: "RipTide",
  HydroSlicer: "HydroSlicer",
  TorrentialBlast: "DiversionLaser",
  Crosswind: "CrossWind",
  FreezeWall: "IceWall",
  SmokeJet: "Unique_OctopursGirl_InkJet",
  HydroSpin: "Unique_TentacleTurtle_HydroSpin",
  KonohaFlip: "Unique_LeafMomonga_SomerSault",
  HighBreach: "Unique_IceNarwhal_JumpingHorn",
  LanternSweep: "Unique_GhostAnglerfish_SweepBait",
  TriggerHappy: "Unique_StuffedShark_HiddenWeapon",
  DarkShot: "GravityShot",
  ThunderSpear: "ThunderSpear",
  ReflectLeaf: "ReflectiveShuriken",
  UnknownSkillHealingTree: "HealingTree",
  ChaoticSpray: "Unique_IceCrocodile_SpitAttack",
  UnknownSkillUniqueYakushimaBoss002PhantasmalDeathray: "Unique_YakushimaBoss002_PhantasmalDeathray",
  UnknownSkillUniqueYakushimaBoss002PhantasmalEye: "Unique_YakushimaBoss002_PhantasmalEye",
  UnknownSkillUniqueYakushimaBoss002PhantasmalBolt: "Unique_YakushimaBoss002_PhantasmalBolt",
  UnknownSkillUniqueYakushimaBoss002PhantasmalSphere: "Unique_YakushimaBoss002_PhantasmalSphere",
  LockOnLunge: "Unique_Yakushima_EyeTossin",
  ServantCall: "Unique_Yakushima_SummonServant",
  ScorchingLanternSweep: "Unique_GhostAnglerfish_Fire_SweepBait_Fire",
  Thunderslide: "Unique_CaptainPenguin_Black_BodySlide_Electric",
  DeepBreath: "Unique_Plesiosaur_LongBreath",
  DashKick: "Unique_TropicalOstrich_DashKick",
  FrenziedCharge: "Unique_Yakushima_MouthTossin",
  UnknownSkillUniqueYakushimaBoss001GreenPhantasmalBolt: "Unique_YakushimaBoss001_Green_PhantasmalBolt",
  UnknownSkillUniqueYakushimaBoss001GreenPhantasmalEye: "Unique_YakushimaBoss001_Green_PhantasmalEye",
  UnknownSkillUniqueYakushimaBoss001GreenPhantasmalSphere: "Unique_YakushimaBoss001_Green_PhantasmalSphere",
  UnknownSkillUniqueYakushimaBoss001GreenPhantasmalDeathray: "Unique_YakushimaBoss001_Green_PhantasmalDeathray",
  ThalassonicLaser: "Unique_PoseidonOrca_TorrentLaser",
  SlimePressNeutral: "Unique_YakushimaMonster001_SlimePress_Normal",
  SlimePressGrass: "Unique_YakushimaMonster001_SlimePress_Leaf",
  SlimePressWater: "Unique_YakushimaMonster001_SlimePress_Water",
  SlimePressFire: "Unique_YakushimaMonster001_SlimePress_Fire",
  SlimePressDark: "Unique_YakushimaMonster001_SlimePress_Dark",
  SlimePressRainbow: "Unique_YakushimaMonster001_SlimePress_Rainbow",
  OcularRush: "Unique_YakushimaBoss001_Small_DemonEyeCharge",
  SwordCharge: "Unique_YakushimaMonster002_SwordCharge",
  WingedAssault: "Unique_YakushimaMonster003_BatCharge",
  FireTackle: "Unique_BluePlatypus_Toboggan_Fire",
  SentinelOfTheGreatSea: "PARTNERSKILL_PoseidonOrca",
  UnknownSkillPoseidonOrcaPartnerSkillSpearBullet: "PoseidonOrca_PartnerSkill_SpearBullet",
  UnknownSkillHumanRolling: "Human_Rolling",
  UseWeapon: "Weapon_Use",
  LightningSmash: "Unique_FlowerDinosaur_Electric_ThunderWhip",
  FrozenPress: "Unique_KingAlpaca_Ice_IcePress",
  NightmareClaw: "Unique_Baphomet_Dark_DarkKite",
  SplashTackle: "Unique_SakuraSaurus_Water_SplashTackle",
  MudHorn: "Unique_Deer_Ground_DirtyHorn",
  RumbleCombo: "Unique_Gorilla_Ground_EarthPunch",
  DarkWing: "Unique_IceHorse_Dark_DarkBladeAttack",
  UnknownSkillUniqueYakushimaBoss0022PhantasmalDeathray: "Unique_YakushimaBoss002_2_PhantasmalDeathray",
  UnknownSkillUniqueYakushimaBoss0022PhantasmalEye: "Unique_YakushimaBoss002_2_PhantasmalEye",
  UnknownSkillUniqueYakushimaBoss0022PhantasmalBolt: "Unique_YakushimaBoss002_2_PhantasmalBolt",
  UnknownSkillUniqueYakushimaBoss0022PhantasmalSphere: "Unique_YakushimaBoss002_2_PhantasmalSphere",
  UnknownSkillUniqueYakushimaBoss001Green2PhantasmalBolt: "Unique_YakushimaBoss001_Green_2_PhantasmalBolt",
  UnknownSkillUniqueYakushimaBoss001Green2PhantasmalEye: "Unique_YakushimaBoss001_Green_2_PhantasmalEye",
  UnknownSkillUniqueYakushimaBoss001Green2PhantasmalSphere: "Unique_YakushimaBoss001_Green_2_PhantasmalSphere",
  UnknownSkillUniqueYakushimaBoss001Green2PhantasmalDeathray: "Unique_YakushimaBoss001_Green_2_PhantasmalDeathray",
  DoubleFang: "Unique_Garm_BiteV2",
  DoubleFangElectric: "Unique_ThunderDog_BiteV2",
  FierceFangElectric: "Unique_ThunderDog_Bite",
  FierceFangUniqueGuardianDogBite: "Unique_GuardianDog_Bite",
  DoubleFangUniqueGuardianDogBiteV2: "Unique_GuardianDog_BiteV2",
  FierceFangGround: "Unique_GoldenHorse_Bite",
  DoubleFangGround: "Unique_GoldenHorse_BiteV2",
  FierceFangFire: "Unique_AmaterasuWolf_Bite",
  DoubleFangFire: "Unique_AmaterasuWolf_BiteV2",
  FierceFangDark: "Unique_AmaterasuWolf_Dark_Bite",
  DoubleFangDark: "Unique_AmaterasuWolf_Dark_BiteV2",
  FierceFangDarkUniqueBlackPuppyBite: "Unique_BlackPuppy_Bite",
  DoubleFangDarkUniqueBlackPuppyBiteV2: "Unique_BlackPuppy_BiteV2",
  MagmaLaser: "Unique_VolcanoDragon_VolcanicLaser",
  MagmaSpit: "Unique_VolcanoDragon_MagmaSpit",
  SomersaultScratch: "Unique_Sekhmet_SomersaultScratch",
  RollingScratch: "Unique_Sekhmet_RollingScratch",
  SpectralSteed: "Unique_NightBlueHorse_Tossin",
  FlashCharge: "Unique_BlueThunderHorse_Tossin",
  SacredRain: "Unique_LegendDeer_WarpPillarBurst",
  DivineWing: "Unique_LegendDeer_RadiantWingRush",
  UnknownSkillUniqueLegendDeerBarrierReleaseNormal: "Unique_LegendDeer_BarrierRelease_Normal",
  UnknownSkillUniqueLegendDeerBarrierReleaseGrass: "Unique_LegendDeer_BarrierRelease_Grass",
  UnknownSkillUniqueLegendDeerBarrierReleaseWater: "Unique_LegendDeer_BarrierRelease_Water",
  PurifyingLight: "Unique_LegendDeer_RadiantPurge_Otomo",
  RadiantBarrage: "RadiantBarrage",
  BlackQuilledBallet: "Unique_MonochromeQueen_BalletJump",
  RootCannon: "Unique_GrassGolem_ArmCannon",
  RocketArm: "Unique_GrassGolem_RocketPunch",
  Maelstrom: "Unique_KingWhale_Maelstrom",
  BubbleRain: "Unique_KingWhale_HomingBubble",
  AquaTornado: "Unique_KingWhale_AquaTornado",
  UnknownSkillUniqueKingWhaleTidalBore: "Unique_KingWhale_TidalBore",
  IaigiriUniqueRoninIaiPartnerSkill: "Unique_Ronin_Iai_PartnerSkill",
  TidalCharge: "Unique_KingWhale_WaveTackle",
  GrandBreach: "Unique_KingWhale_Breaching",
  AquaBlade: "Unique_KingWhale_AquaBlade",
  ThunderUppercut: "Unique_ScorpionMan_Erectric_UpperThunder",
  RoyalStep: "Unique_NightBlueHorse_Neutral_AirStep",
  SilverSteed: "Unique_NightBlueHorse_Neutral_Tossin",
  FierceFangGroundUniqueSamuraiDogBite: "Unique_SamuraiDog_Bite",
  DoubleFangGroundUniqueSamuraiDogBiteV2: "Unique_SamuraiDog_BiteV2",
  Frostcall: "Unique_ThunderDog_Ice_KoriShorai",
  IceGaleStrike: "Unique_Kirin_Ice_IceTackle",
  CreepingBubbles: "CreepingBubble",
  DoubleFangIce: "Unique_ThunderDog_Ice_BiteV2",
  FierceFangIce: "Unique_ThunderDog_Ice_Bite",
  WindBurst: "WindBurst",
  FuddlerTunneler: "Unique_CuteMole_DiggingAttack",
  PersistentSlash: "Unique_SamuraiDog_DashSlash",
  PoisonScatter: "Unique_SnakeGirl_SnakeShot",
  MummyRush: "Unique_MummyPal_MummyAttack",
  TricksterShow: "Unique_ClownRabbit_TrickShow",
  CubePress: "Unique_CubeTurtle_CubePress",
  UnknownSkillUniqueKingWhaleSuperTidalBore: "Unique_KingWhale_SuperTidalBore",
  ForestLaser: "PARTNERSKILL_GrassGolem",
  SumoStomp: "Unique_SumoDog_SumoStomp",
  HornBurst: "Unique_RockBeast_RockHorn",
  IceBurst: "Unique_RockBeast_Ice_IceHorn",
  FierceFangElectricUniqueElecPomeranianBite: "Unique_ElecPomeranian_Bite",
  DoubleFangElectricUniqueElecPomeranianBiteV2: "Unique_ElecPomeranian_BiteV2",
  LanternFlame: "Unique_LanternButler_LanternFlame",
  HydraCharge: "Unique_BlueSkyDragon_Tossin",
  AzureDracoflare: "Unique_BlueSkyDragon_SweepBreath",
  CelestialVortex: "Unique_BlueSkyDragon_DrainStorm",
  FlowerStomp: "Unique_RedFlowerBird_JumpKick",
  FlameCutter: "Unique_WingGolem_Fire_FlameCutter",
  IceLaser: "Unique_VolcanoDragon_Ice_IceLaser",
  IceSpit: "Unique_VolcanoDragon_Ice_IcicleSpit",
  HolyPress: "Unique_CubeTurtle_Neutral_HolyPress",
  DarkRoot: "Unique_GrassGolem_Dark_DarkArmCannon",
  UnknownSkillUniqueWorldTreeDragonPaldiumShot: "Unique_WorldTreeDragon_PaldiumShot",
  UnknownSkillUniqueWorldTreeDragonPaldiumCannon: "Unique_WorldTreeDragon_PaldiumCannon",
  UnknownSkillUniqueWorldTreeDragonSupernova: "Unique_WorldTreeDragon_Supernova",
  UnknownSkillUniqueWorldTreeDragonHaloBeam: "Unique_WorldTreeDragon_HaloBeam",
  UnknownSkillUniqueWorldTreeDragonPaldiumRain: "Unique_WorldTreeDragon_PaldiumRain",
  UnknownSkillUniqueWorldTreeDragonLaserGliding: "Unique_WorldTreeDragon_LaserGliding",
  UnknownSkillUniqueWorldTreeDragonHaloCutter: "Unique_WorldTreeDragon_HaloCutter",
  UnknownSkillUniqueWorldTreeDragonPaldiumExplosion: "Unique_WorldTreeDragon_PaldiumExplosion",
  CorruptionLaser: "PARTNERSKILL_GrassGolem_Dark",
  UnknownSkillUniqueLilyQueenLilyHealingBoss: "Unique_LilyQueen_LilyHealing_Boss",
  GlacialPlunge: "Unique_ThunderBird_Ice_SnowStrom",
  DarkNova: "Unique_WhiteDeer_Dark_DarkPillar",
  GiantSpore: "Unique_Mothman_GiantSpore",
  SporeBurst: "Unique_Mothman_SporeScatter",
  UnknownSkillUniqueMoonQueenGYMHardAct: "Unique_MoonQueen_GYM_Hard_Act",
  PoisonPromenade: "Unique_FlowerPrince_PoisonGasTackle",
  ToxicDance: "Unique_FlowerPrince_PoisonGasDance",
  RagingBullRush: "Unique_GrassMinotaur_BullRush",
  RagingSnowRush: "Unique_GrassMinotaur_Ice_BullRush",
  LotusBloom: "Unique_LotusDragon_LotusBloom",
  TailSlash: "Unique_GhostDragon_TailSlash",
  BlazingBeam: "Unique_GhostDragon_PhosphorousBeam",
  BullRush: "Unique_GrassMinotaur_BullRush_Lower",
  SnowRush: "Unique_GrassMinotaur_Ice_BullRush_Lower",
  UnknownSkillUniqueWorldTreeDragonBigBang: "Unique_WorldTreeDragon_BigBang",
  MissileBurst: "Unique_DomeArmorDragon_ExplosiveMissile",
  RapidKick: "Unique_PandaGirl_RapidKick",
  ShellCharge: "Unique_ElecSnail_ShellCharge",
} as const;

export type SkillId = (typeof SkillId)[keyof typeof SkillId];

export const SKILL_ID_TO_NAME: Record<SkillId, string> = {
  [SkillId.EnTextTidalWave]: "en Text (TidalWave)",
  [SkillId.UnknownSkillWaterWave]: "Unknown Skill (WaterWave)",
  [SkillId.HydroJet]: "Hydro Jet",
  [SkillId.AquaGun]: "Aqua Gun",
  [SkillId.BubbleBlast]: "Bubble Blast",
  [SkillId.AcidRain]: "Acid Rain",
  [SkillId.AquaBurst]: "Aqua Burst",
  [SkillId.SurfingSlam]: "Surfing Slam",
  [SkillId.HydroLaser]: "Hydro Laser",
  [SkillId.Intimidate]: "Intimidate",
  [SkillId.Punch]: "Punch",
  [SkillId.AirCannon]: "Air Cannon",
  [SkillId.ChickenRush]: "Chicken Rush",
  [SkillId.PowerShot]: "Power Shot",
  [SkillId.RolyPoly]: "Roly Poly",
  [SkillId.PunchFlurry]: "Punch Flurry",
  [SkillId.FluffyTackle]: "Fluffy Tackle",
  [SkillId.FierceFang]: "Fierce Fang",
  [SkillId.AntlerUppercut]: "Antler Uppercut",
  [SkillId.RecklessCharge]: "Reckless Charge",
  [SkillId.GaleClaw]: "Gale Claw",
  [SkillId.CatPress]: "Cat Press",
  [SkillId.EnTextThrow]: "en Text (Throw)",
  [SkillId.TornadoAttack]: "Tornado Attack",
  [SkillId.PowerBomb]: "Power Bomb",
  [SkillId.MuscleSlam]: "Muscle Slam",
  [SkillId.GroundPound]: "Ground Pound",
  [SkillId.CloudTempest]: "Cloud Tempest",
  [SkillId.EnTextScratch]: "en Text (Scratch)",
  [SkillId.UnknownSkillWorkAttack]: "Unknown Skill (WorkAttack)",
  [SkillId.KinglySlam]: "Kingly Slam",
  [SkillId.SpearThrust]: "Spear Thrust",
  [SkillId.PalBlast]: "Pal Blast",
  [SkillId.Implode]: "Implode",
  [SkillId.BeeQuiet]: "Bee Quiet",
  [SkillId.MegatonImplode]: "Megaton Implode",
  [SkillId.WindCutter]: "Wind Cutter",
  [SkillId.SeedMachineGun]: "Seed Machine Gun",
  [SkillId.BotanicalSmash]: "Botanical Smash",
  [SkillId.Multicutter]: "Multicutter",
  [SkillId.SeedMine]: "Seed Mine",
  [SkillId.FocusShot]: "Focus Shot",
  [SkillId.SpinningStaff]: "Spinning Staff",
  [SkillId.GrassTornado]: "Grass Tornado",
  [SkillId.CrushingPunch]: "Crushing Punch",
  [SkillId.SpineVine]: "Spine Vine",
  [SkillId.SolarBlast]: "Solar Blast",
  [SkillId.EnTextSnowStorm]: "en Text (SnowStorm)",
  [SkillId.IceMissile]: "Ice Missile",
  [SkillId.IceMissileIceMissile]: "Ice Missile",
  [SkillId.IcicleCutter]: "Icicle Cutter",
  [SkillId.FreezingCharge]: "Freezing Charge",
  [SkillId.Iceberg]: "Iceberg",
  [SkillId.EmperorSlide]: "Emperor Slide",
  [SkillId.CrystalBreath]: "Crystal Breath",
  [SkillId.FrostBurst]: "Frost Burst",
  [SkillId.CrystalWing]: "Crystal Wing",
  [SkillId.BlizzardSpike]: "Blizzard Spike",
  [SkillId.IgnisBlast]: "Ignis Blast",
  [SkillId.SpiritFire]: "Spirit Fire",
  [SkillId.BlazingHorn]: "Blazing Horn",
  [SkillId.FlareArrow]: "Flare Arrow",
  [SkillId.Iaigiri]: "Iaigiri",
  [SkillId.IgnisBreath]: "Ignis Breath",
  [SkillId.HellfireClaw]: "Hellfire Claw",
  [SkillId.DaringFlames]: "Daring Flames",
  [SkillId.FlareStorm]: "Flare Storm",
  [SkillId.IgnisCharge]: "Ignis Charge",
  [SkillId.VolcanicBurst]: "Volcanic Burst",
  [SkillId.IgnisRage]: "Ignis Rage",
  [SkillId.PhoenixFlare]: "Phoenix Flare",
  [SkillId.FireBall]: "Fire Ball",
  [SkillId.CrossLightning]: "Cross Lightning",
  [SkillId.ThunderRain]: "Thunder Rain",
  [SkillId.SparkBlast]: "Spark Blast",
  [SkillId.UnknownSkillFunnelRaijinDaughter]: "Unknown Skill (Funnel_RaijinDaughter)",
  [SkillId.Shockwave]: "Shockwave",
  [SkillId.ElectricBall]: "Electric Ball",
  [SkillId.PlasmaFunnel]: "Plasma Funnel",
  [SkillId.LockOnLaser]: "Lock-on Laser",
  [SkillId.LightningClaw]: "Lightning Claw",
  [SkillId.LightningStreak]: "Lightning Streak",
  [SkillId.BlastPunch]: "Blast Punch",
  [SkillId.TriLightning]: "Tri-Lightning",
  [SkillId.LightningGale]: "Lightning Gale",
  [SkillId.Kerauno]: "Kerauno",
  [SkillId.LightningStrike]: "Lightning Strike",
  [SkillId.LightningBolt]: "Lightning Bolt",
  [SkillId.BogBlast]: "Bog Blast",
  [SkillId.StoneBlast]: "Stone Blast",
  [SkillId.ShellSpin]: "Shell Spin",
  [SkillId.StoneCannon]: "Stone Cannon",
  [SkillId.GigaHorn]: "Giga Horn",
  [SkillId.SandTornado]: "Sand Tornado",
  [SkillId.SpinningRoundhouse]: "Spinning Roundhouse",
  [SkillId.EarthImpact]: "Earth Impact",
  [SkillId.ForcefulCharge]: "Forceful Charge",
  [SkillId.GroundSmash]: "Ground Smash",
  [SkillId.RockLance]: "Rock Lance",
  [SkillId.DragonCannon]: "Dragon Cannon",
  [SkillId.DragonBurst]: "Dragon Burst",
  [SkillId.DragonBreath]: "Dragon Breath",
  [SkillId.MysticWhirlwind]: "Mystic Whirlwind",
  [SkillId.BeamComet]: "Beam Comet",
  [SkillId.DragonMeteor]: "Dragon Meteor",
  [SkillId.PoisonFog]: "Poison Fog",
  [SkillId.UnknownSkillFunnelDreamDemon]: "Unknown Skill (Funnel_DreamDemon)",
  [SkillId.PoisonBlast]: "Poison Blast",
  [SkillId.DarkBall]: "Dark Ball",
  [SkillId.ShadowBurst]: "Shadow Burst",
  [SkillId.PhantomPeck]: "Phantom Peck",
  [SkillId.JumpingClaw]: "Jumping Claw",
  [SkillId.SpiritFlame]: "Spirit Flame",
  [SkillId.DarkCharge]: "Dark Charge",
  [SkillId.NightmareBall]: "Nightmare Ball",
  [SkillId.PsychoGravity]: "Psycho Gravity",
  [SkillId.TwinSpears]: "Twin Spears",
  [SkillId.DarkLaser]: "Dark Laser",
  [SkillId.DivineDisaster]: "Divine Disaster",
  [SkillId.DarkWhisp]: "Dark Whisp",
  [SkillId.RocketSlam]: "Rocket Slam",
  [SkillId.Rockburst]: "Rockburst",
  [SkillId.DiamondRain]: "Diamond Rain",
  [SkillId.BeamSlicer]: "Beam Slicer",
  [SkillId.NightmareBloom]: "Nightmare Bloom",
  [SkillId.FlameWaltz]: "Flame Waltz",
  [SkillId.CometStrike]: "Comet Strike",
  [SkillId.UmbralSurge]: "Umbral Surge",
  [SkillId.DarkCannon]: "Dark Cannon",
  [SkillId.DarkArrow]: "Dark Arrow",
  [SkillId.Apocalypse]: "Apocalypse",
  [SkillId.NightmareRay]: "Nightmare Ray",
  [SkillId.JumpingStinger]: "Jumping Stinger",
  [SkillId.StarMine]: "Star Mine",
  [SkillId.EarthDash]: "Earth Dash",
  [SkillId.CircleVine]: "Circle Vine",
  [SkillId.Polykeraunos]: "Polykeraunos",
  [SkillId.MagnaCrush]: "Magna Crush",
  [SkillId.Splash]: "Splash",
  [SkillId.ChargeCannon]: "Charge Cannon",
  [SkillId.BrawnImpact]: "Brawn Impact",
  [SkillId.GroundCutter]: "Ground Cutter",
  [SkillId.BlastCannon]: "Blast Cannon",
  [SkillId.CometBarrage]: "Comet Barrage",
  [SkillId.Meteorain]: "Meteorain",
  [SkillId.VolcanicRain]: "Volcanic Rain",
  [SkillId.HeavyThunderTank]: "Heavy Thunder Tank",
  [SkillId.BountifulProtection]: "Bountiful Protection",
  [SkillId.HolyBurst]: "Holy Burst",
  [SkillId.EvilSlash]: "Evil Slash",
  [SkillId.MoonlightBeam]: "Moonlight Beam",
  [SkillId.FlameWall]: "Flame Wall",
  [SkillId.AirBlade]: "Air Blade",
  [SkillId.SeigetsuBlade]: "Seigetsu Blade",
  [SkillId.WholeheartedStance]: "Wholehearted Stance",
  [SkillId.CurtainSplash]: "Curtain Splash",
  [SkillId.TriSpark]: "TriSpark",
  [SkillId.Thunderstorm]: "Thunderstorm",
  [SkillId.UpperSmash]: "Upper Smash",
  [SkillId.FlameFunnel]: "Flame Funnel",
  [SkillId.SandTwister]: "Sand Twister",
  [SkillId.AllRangeThunder]: "All Range Thunder",
  [SkillId.ThunderRail]: "Thunder Rail",
  [SkillId.LethalLaser]: "Lethal Laser",
  [SkillId.PoisonShower]: "Poison Shower",
  [SkillId.UnknownSkillWaterBalloon]: "Unknown Skill (WaterBalloon)",
  [SkillId.IcicleBullet]: "Icicle Bullet",
  [SkillId.DoubleBlizzardSpike]: "Double Blizzard Spike",
  [SkillId.AbsoluteFrost]: "Absolute Frost",
  [SkillId.RaidCutter]: "Raid Cutter",
  [SkillId.WindEdge]: "Wind Edge",
  [SkillId.FlareTwister]: "Flare Twister",
  [SkillId.RagingFlameWave]: "Raging Flame Wave",
  [SkillId.DivineDisasterII]: "Divine Disaster II",
  [SkillId.SeigetsuFlash]: "Seigetsu Flash",
  [SkillId.IcicleLine]: "Icicle Line",
  [SkillId.VolcanicFang]: "Volcanic Fang",
  [SkillId.LightningDive]: "Lightning Dive",
  [SkillId.WindBarrier]: "Wind Barrier",
  [SkillId.FirefistBreathstorm]: "Firefist Breathstorm",
  [SkillId.LeapingRoundhouse]: "Leaping Roundhouse",
  [SkillId.SnowBowling]: "Snow Bowling",
  [SkillId.SlitherSlam]: "Slither Slam",
  [SkillId.NeedleSpear]: "Needle Spear",
  [SkillId.RushBeak]: "Rush Beak",
  [SkillId.BeckonLightning]: "Beckon Lightning",
  [SkillId.SpiritDash]: "Spirit Dash",
  [SkillId.FlameBreath]: "Flame Breath",
  [SkillId.BlizzardClaw]: "Blizzard Claw",
  [SkillId.SatelliteBit]: "Satellite Bit",
  [SkillId.OmegaLaser]: "Omega Laser",
  [SkillId.AstralRay]: "Astral Ray",
  [SkillId.BeamSlash]: "Beam Slash",
  [SkillId.CosmicMeteor]: "Cosmic Meteor",
  [SkillId.TempestBlizzard]: "Tempest Blizzard",
  [SkillId.MagmaSerpent]: "Magma Serpent",
  [SkillId.PredatorSurge]: "Predator Surge",
  [SkillId.PredatorBlast]: "Predator Blast",
  [SkillId.PredatorMark]: "Predator Mark",
  [SkillId.StoneClaw]: "Stone Claw",
  [SkillId.ThunderTempest]: "Thunder Tempest",
  [SkillId.SnowClaw]: "Snow Claw",
  [SkillId.PhoenixTide]: "Phoenix Tide",
  [SkillId.DaringShadowstorm]: "Daring Shadowstorm",
  [SkillId.RockyImpact]: "Rocky Impact",
  [SkillId.LawnBowling]: "Lawn Bowling",
  [SkillId.GlacialImpact]: "Glacial Impact",
  [SkillId.WebstrikeImpact]: "Webstrike Impact",
  [SkillId.FrostTalon]: "Frost Talon",
  [SkillId.SoulDrain]: "Soul Drain",
  [SkillId.GrudgeBarrage]: "Grudge Barrage",
  [SkillId.AegisCharge]: "Aegis Charge",
  [SkillId.BoltBlink]: "Bolt Blink",
  [SkillId.HolyNova]: "Holy Nova",
  [SkillId.LethalStep]: "Lethal Step",
  [SkillId.CrashDash]: "Crash Dash",
  [SkillId.UnknownSkillFunnelRaijinDaughterWater]: "Unknown Skill (Funnel_RaijinDaughter_Water)",
  [SkillId.PlasmaDash]: "Plasma Dash",
  [SkillId.GeyserGush]: "Geyser Gush",
  [SkillId.AquaSurge]: "Aqua Surge",
  [SkillId.HydroSlicer]: "Hydro Slicer",
  [SkillId.TorrentialBlast]: "Torrential Blast",
  [SkillId.Crosswind]: "Crosswind",
  [SkillId.FreezeWall]: "Freeze Wall",
  [SkillId.SmokeJet]: "Smoke Jet",
  [SkillId.HydroSpin]: "Hydro Spin",
  [SkillId.KonohaFlip]: "Konoha Flip",
  [SkillId.HighBreach]: "High Breach",
  [SkillId.LanternSweep]: "Lantern Sweep",
  [SkillId.TriggerHappy]: "Trigger Happy",
  [SkillId.DarkShot]: "Dark Shot",
  [SkillId.ThunderSpear]: "Thunder Spear",
  [SkillId.ReflectLeaf]: "Reflect Leaf",
  [SkillId.UnknownSkillHealingTree]: "Unknown Skill (HealingTree)",
  [SkillId.ChaoticSpray]: "Chaotic Spray",
  [SkillId.UnknownSkillUniqueYakushimaBoss002PhantasmalDeathray]: "Unknown Skill (Unique_YakushimaBoss002_PhantasmalDeathray)",
  [SkillId.UnknownSkillUniqueYakushimaBoss002PhantasmalEye]: "Unknown Skill (Unique_YakushimaBoss002_PhantasmalEye)",
  [SkillId.UnknownSkillUniqueYakushimaBoss002PhantasmalBolt]: "Unknown Skill (Unique_YakushimaBoss002_PhantasmalBolt)",
  [SkillId.UnknownSkillUniqueYakushimaBoss002PhantasmalSphere]: "Unknown Skill (Unique_YakushimaBoss002_PhantasmalSphere)",
  [SkillId.LockOnLunge]: "Lock-On Lunge",
  [SkillId.ServantCall]: "Servant Call",
  [SkillId.ScorchingLanternSweep]: "Scorching Lantern Sweep",
  [SkillId.Thunderslide]: "Thunderslide",
  [SkillId.DeepBreath]: "Deep Breath",
  [SkillId.DashKick]: "Dash Kick",
  [SkillId.FrenziedCharge]: "Frenzied Charge",
  [SkillId.UnknownSkillUniqueYakushimaBoss001GreenPhantasmalBolt]: "Unknown Skill (Unique_YakushimaBoss001_Green_PhantasmalBolt)",
  [SkillId.UnknownSkillUniqueYakushimaBoss001GreenPhantasmalEye]: "Unknown Skill (Unique_YakushimaBoss001_Green_PhantasmalEye)",
  [SkillId.UnknownSkillUniqueYakushimaBoss001GreenPhantasmalSphere]: "Unknown Skill (Unique_YakushimaBoss001_Green_PhantasmalSphere)",
  [SkillId.UnknownSkillUniqueYakushimaBoss001GreenPhantasmalDeathray]: "Unknown Skill (Unique_YakushimaBoss001_Green_PhantasmalDeathray)",
  [SkillId.ThalassonicLaser]: "Thalassonic Laser",
  [SkillId.SlimePressNeutral]: "Slime Press (Neutral)",
  [SkillId.SlimePressGrass]: "Slime Press (Grass)",
  [SkillId.SlimePressWater]: "Slime Press (Water)",
  [SkillId.SlimePressFire]: "Slime Press (Fire)",
  [SkillId.SlimePressDark]: "Slime Press (Dark)",
  [SkillId.SlimePressRainbow]: "Slime Press (Rainbow)",
  [SkillId.OcularRush]: "Ocular Rush",
  [SkillId.SwordCharge]: "Sword Charge",
  [SkillId.WingedAssault]: "Winged Assault",
  [SkillId.FireTackle]: "Fire Tackle",
  [SkillId.SentinelOfTheGreatSea]: "Sentinel of the Great Sea",
  [SkillId.UnknownSkillPoseidonOrcaPartnerSkillSpearBullet]: "Unknown Skill (PoseidonOrca_PartnerSkill_SpearBullet)",
  [SkillId.UnknownSkillHumanRolling]: "Unknown Skill (Human_Rolling)",
  [SkillId.UseWeapon]: "Use Weapon",
  [SkillId.LightningSmash]: "Lightning Smash",
  [SkillId.FrozenPress]: "Frozen Press",
  [SkillId.NightmareClaw]: "Nightmare Claw",
  [SkillId.SplashTackle]: "Splash Tackle",
  [SkillId.MudHorn]: "Mud Horn",
  [SkillId.RumbleCombo]: "Rumble Combo",
  [SkillId.DarkWing]: "Dark Wing",
  [SkillId.UnknownSkillUniqueYakushimaBoss0022PhantasmalDeathray]: "Unknown Skill (Unique_YakushimaBoss002_2_PhantasmalDeathray)",
  [SkillId.UnknownSkillUniqueYakushimaBoss0022PhantasmalEye]: "Unknown Skill (Unique_YakushimaBoss002_2_PhantasmalEye)",
  [SkillId.UnknownSkillUniqueYakushimaBoss0022PhantasmalBolt]: "Unknown Skill (Unique_YakushimaBoss002_2_PhantasmalBolt)",
  [SkillId.UnknownSkillUniqueYakushimaBoss0022PhantasmalSphere]: "Unknown Skill (Unique_YakushimaBoss002_2_PhantasmalSphere)",
  [SkillId.UnknownSkillUniqueYakushimaBoss001Green2PhantasmalBolt]: "Unknown Skill (Unique_YakushimaBoss001_Green_2_PhantasmalBolt)",
  [SkillId.UnknownSkillUniqueYakushimaBoss001Green2PhantasmalEye]: "Unknown Skill (Unique_YakushimaBoss001_Green_2_PhantasmalEye)",
  [SkillId.UnknownSkillUniqueYakushimaBoss001Green2PhantasmalSphere]: "Unknown Skill (Unique_YakushimaBoss001_Green_2_PhantasmalSphere)",
  [SkillId.UnknownSkillUniqueYakushimaBoss001Green2PhantasmalDeathray]: "Unknown Skill (Unique_YakushimaBoss001_Green_2_PhantasmalDeathray)",
  [SkillId.DoubleFang]: "Double Fang",
  [SkillId.DoubleFangElectric]: "Double Fang (Electric)",
  [SkillId.FierceFangElectric]: "Fierce Fang (Electric)",
  [SkillId.FierceFangUniqueGuardianDogBite]: "Fierce Fang",
  [SkillId.DoubleFangUniqueGuardianDogBiteV2]: "Double Fang",
  [SkillId.FierceFangGround]: "Fierce Fang (Ground)",
  [SkillId.DoubleFangGround]: "Double Fang (Ground)",
  [SkillId.FierceFangFire]: "Fierce Fang (Fire)",
  [SkillId.DoubleFangFire]: "Double Fang (Fire)",
  [SkillId.FierceFangDark]: "Fierce Fang (Dark)",
  [SkillId.DoubleFangDark]: "Double Fang (Dark)",
  [SkillId.FierceFangDarkUniqueBlackPuppyBite]: "Fierce Fang (Dark)",
  [SkillId.DoubleFangDarkUniqueBlackPuppyBiteV2]: "Double Fang (Dark)",
  [SkillId.MagmaLaser]: "Magma Laser",
  [SkillId.MagmaSpit]: "Magma Spit",
  [SkillId.SomersaultScratch]: "Somersault Scratch",
  [SkillId.RollingScratch]: "Rolling Scratch",
  [SkillId.SpectralSteed]: "Spectral Steed",
  [SkillId.FlashCharge]: "Flash Charge",
  [SkillId.SacredRain]: "Sacred Rain",
  [SkillId.DivineWing]: "Divine Wing",
  [SkillId.UnknownSkillUniqueLegendDeerBarrierReleaseNormal]: "Unknown Skill (Unique_LegendDeer_BarrierRelease_Normal)",
  [SkillId.UnknownSkillUniqueLegendDeerBarrierReleaseGrass]: "Unknown Skill (Unique_LegendDeer_BarrierRelease_Grass)",
  [SkillId.UnknownSkillUniqueLegendDeerBarrierReleaseWater]: "Unknown Skill (Unique_LegendDeer_BarrierRelease_Water)",
  [SkillId.PurifyingLight]: "Purifying Light",
  [SkillId.RadiantBarrage]: "Radiant Barrage",
  [SkillId.BlackQuilledBallet]: "Black Quilled Ballet",
  [SkillId.RootCannon]: "Root Cannon",
  [SkillId.RocketArm]: "Rocket Arm",
  [SkillId.Maelstrom]: "Maelstrom",
  [SkillId.BubbleRain]: "Bubble Rain",
  [SkillId.AquaTornado]: "Aqua Tornado",
  [SkillId.UnknownSkillUniqueKingWhaleTidalBore]: "Unknown Skill (Unique_KingWhale_TidalBore)",
  [SkillId.IaigiriUniqueRoninIaiPartnerSkill]: "Iaigiri",
  [SkillId.TidalCharge]: "Tidal Charge",
  [SkillId.GrandBreach]: "Grand Breach",
  [SkillId.AquaBlade]: "Aqua Blade",
  [SkillId.ThunderUppercut]: "Thunder Uppercut",
  [SkillId.RoyalStep]: "Royal Step",
  [SkillId.SilverSteed]: "Silver Steed",
  [SkillId.FierceFangGroundUniqueSamuraiDogBite]: "Fierce Fang (Ground)",
  [SkillId.DoubleFangGroundUniqueSamuraiDogBiteV2]: "Double Fang (Ground)",
  [SkillId.Frostcall]: "Frostcall",
  [SkillId.IceGaleStrike]: "Ice Gale Strike",
  [SkillId.CreepingBubbles]: "Creeping Bubbles",
  [SkillId.DoubleFangIce]: "Double Fang (Ice)",
  [SkillId.FierceFangIce]: "Fierce Fang (Ice)",
  [SkillId.WindBurst]: "Wind Burst",
  [SkillId.FuddlerTunneler]: "Fuddler Tunneler",
  [SkillId.PersistentSlash]: "Persistent Slash",
  [SkillId.PoisonScatter]: "Poison Scatter",
  [SkillId.MummyRush]: "Mummy Rush",
  [SkillId.TricksterShow]: "Trickster Show",
  [SkillId.CubePress]: "Cube Press",
  [SkillId.UnknownSkillUniqueKingWhaleSuperTidalBore]: "Unknown Skill (Unique_KingWhale_SuperTidalBore)",
  [SkillId.ForestLaser]: "Forest Laser",
  [SkillId.SumoStomp]: "Sumo Stomp",
  [SkillId.HornBurst]: "Horn Burst",
  [SkillId.IceBurst]: "Ice Burst",
  [SkillId.FierceFangElectricUniqueElecPomeranianBite]: "Fierce Fang (Electric)",
  [SkillId.DoubleFangElectricUniqueElecPomeranianBiteV2]: "Double Fang (Electric)",
  [SkillId.LanternFlame]: "Lantern Flame",
  [SkillId.HydraCharge]: "Hydra Charge",
  [SkillId.AzureDracoflare]: "Azure Dracoflare",
  [SkillId.CelestialVortex]: "Celestial Vortex",
  [SkillId.FlowerStomp]: "Flower Stomp",
  [SkillId.FlameCutter]: "Flame Cutter",
  [SkillId.IceLaser]: "Ice Laser",
  [SkillId.IceSpit]: "Ice Spit",
  [SkillId.HolyPress]: "Holy Press",
  [SkillId.DarkRoot]: "Dark Root",
  [SkillId.UnknownSkillUniqueWorldTreeDragonPaldiumShot]: "Unknown Skill (Unique_WorldTreeDragon_PaldiumShot)",
  [SkillId.UnknownSkillUniqueWorldTreeDragonPaldiumCannon]: "Unknown Skill (Unique_WorldTreeDragon_PaldiumCannon)",
  [SkillId.UnknownSkillUniqueWorldTreeDragonSupernova]: "Unknown Skill (Unique_WorldTreeDragon_Supernova)",
  [SkillId.UnknownSkillUniqueWorldTreeDragonHaloBeam]: "Unknown Skill (Unique_WorldTreeDragon_HaloBeam)",
  [SkillId.UnknownSkillUniqueWorldTreeDragonPaldiumRain]: "Unknown Skill (Unique_WorldTreeDragon_PaldiumRain)",
  [SkillId.UnknownSkillUniqueWorldTreeDragonLaserGliding]: "Unknown Skill (Unique_WorldTreeDragon_LaserGliding)",
  [SkillId.UnknownSkillUniqueWorldTreeDragonHaloCutter]: "Unknown Skill (Unique_WorldTreeDragon_HaloCutter)",
  [SkillId.UnknownSkillUniqueWorldTreeDragonPaldiumExplosion]: "Unknown Skill (Unique_WorldTreeDragon_PaldiumExplosion)",
  [SkillId.CorruptionLaser]: "Corruption Laser",
  [SkillId.UnknownSkillUniqueLilyQueenLilyHealingBoss]: "Unknown Skill (Unique_LilyQueen_LilyHealing_Boss)",
  [SkillId.GlacialPlunge]: "Glacial Plunge",
  [SkillId.DarkNova]: "Dark Nova",
  [SkillId.GiantSpore]: "Giant Spore",
  [SkillId.SporeBurst]: "Spore Burst",
  [SkillId.UnknownSkillUniqueMoonQueenGYMHardAct]: "Unknown Skill (Unique_MoonQueen_GYM_Hard_Act)",
  [SkillId.PoisonPromenade]: "Poison Promenade",
  [SkillId.ToxicDance]: "Toxic Dance",
  [SkillId.RagingBullRush]: "Raging Bull Rush",
  [SkillId.RagingSnowRush]: "Raging Snow Rush",
  [SkillId.LotusBloom]: "Lotus Bloom",
  [SkillId.TailSlash]: "Tail Slash",
  [SkillId.BlazingBeam]: "Blazing Beam",
  [SkillId.BullRush]: "Bull Rush",
  [SkillId.SnowRush]: "Snow Rush",
  [SkillId.UnknownSkillUniqueWorldTreeDragonBigBang]: "Unknown Skill (Unique_WorldTreeDragon_BigBang)",
  [SkillId.MissileBurst]: "Missile Burst",
  [SkillId.RapidKick]: "Rapid Kick",
  [SkillId.ShellCharge]: "Shell Charge",
};
