export const TechnologyId = {
  PrimitiveWorkbench: "Workbench",
  StoneAxe: "Product_Axe_Grade_01",
  StonePickaxe: "Product_Pickaxe_Grade_01",
  HandHeldTorch: "HandTorch",
  WoodenClub: "Battle_MeleeWeapon_Bat",
  Palbox: "PALBOX",
  PalSphere: "Special_PalSphere_Grade_01",
  Campfire: "Product_Cooking_Grade_01",
  WoodenChest: "Infra_ItemChest_Grade_01",
  RepairBench: "RepairBench",
  WoodenStructureSet: "Wooden_houseset",
  PalDressingFacility: "SkinChange",
  OldBow: "Battle_RangeWeapon_Bow1",
  Arrow: "Arrow",
  StoneSpear: "Spear",
  ShoddyBed: "Infra_PlayerBed_Grade_01",
  StrawPalBed: "Infra_PalBed_Grade_01",
  GlobalPalbox: "GlobalPalStorage",
  CommonShield: "Shield_01",
  ClothOutfit: "Battle_Armor_Grade_01_Cloth",
  Cloth: "Battle_Cloth",
  FeedBox: "PalFoodBox",
  BerryPlantation: "Product_Farm_Berries",
  Ranch: "MonsterFarm",
  NormalParachute: "Battle_Glider_Grade_01",
  WoodenLivingRoomFurnitureSet: "FurnitureSet_1",
  WoodenTavernFurnitureSet: "FurnitureSet_3",
  WoodenTavernCabinetFurnitureSet: "FurnitureSet_2",
  PalGearWorkbench: "Product_WorkBench_SkillUnlock",
  FireArrow: "Arrow_Fire",
  MountedTorch: "Torch",
  Sign: "Signboard",
  WallMountedSign: "WallSignboard",
  RushoarSaddle: "SkillUnlock_Boar",
  FoxparksHarness: "SkillUnlock_Kitsunebi",
  HouseplantSet: "FurnitureSet_9",
  MonitoringStand: "BaseCampWorkHard",
  Bat: "Battle_MeleeWeapon_Bat2",
  LoggingSite: "Product_StationDeforest",
  StonePit: "Product_StonePit",
  Sandbag: "DefenseWait",
  AlarmBell: "BaseCampBattleDirector",
  MelpacaSaddle: "SkillUnlock_Alpaca",
  WallMountedHouseplantSet: "FurnitureSet_4",
  Crusher: "Crusher",
  PoisonArrow: "Arrow_Poison",
  WoodenDefensiveWall: "DefenseWall_Wood",
  WoodenGate: "Wood_Gate",
  HangingTrap: "Trap_Noose",
  FireplaceSet: "FurnitureSet_28",
  StatueOfPower: "BuildableGoddessStatue",
  SmallFeedBag: "AutoMealPouch_Tier1",
  TropicalOutfit: "Battle_Armor_Grade_01_Cloth_Heat",
  TundraOutfit: "Battle_Armor_Grade_01_Cloth_Cold",
  HotSpring: "Spa",
  DirehowlSSaddledHarness: "SkillUnlock_Garm",
  CarpetSet: "FurnitureSet_17",
  PrimitiveFurnace: "Product_Ingot_Grade_01_Copper",
  ThreeShotBow: "Battle_RangeWeapon_Bow3",
  FeatheredHairBand: "Battle_Helm_Grade_02_Fur",
  Nail: "Infra_MachineParts",
  Ladder: "Wooden_ladder",
  BearTrapSmall: "Trap_LegHold",
  EggIncubator: "Special_HatchingPalEgg",
  AntiqueStorageSet: "FurnitureSet_21",
  MetalAxe: "Product_Axe_Grade_02",
  MetalPickaxe: "Product_Pickaxe_Grade_02",
  HighQualityWorkbench: "Product_Factory_Hard_Grade_01",
  RayneSyndicateFlagSet: "HunterFlagSet",
  ChilletSaddle: "SkillUnlock_WeaselDragon",
  LifmunkSSubmachineGun: "SkillUnlock_Carbunclo",
  AntiqueChairSet: "FurnitureSet_19",
  PeltArmor: "Battle_Armor_Grade_02_Fur",
  MeatCleaver: "MeatCutterKnife",
  MedievalMedicineWorkbench: "Product_Medicine_Grade_01",
  TanzeeSAssaultRifle: "SkillUnlock_Monkey",
  EikthyrdeerSaddle: "SkillUnlock_Deer",
  GrapplingGun: "GrapplingGun",
  FauxGreenerySet: "FurnitureTree_Green",
  TidyTableSet: "TableCircular",
  Crossbow: "Battle_RangeWeapon_BowGun",
  MetalSpear: "Spear_2",
  MetalChest: "Infra_ItemChest_Grade_02",
  CoolerBox: "CoolerBox",
  TrainingDummy: "DamagedScarecrow",
  TanzeeIgnisSAssaultRifle: "SkillUnlock_Monkey_Fire",
  AntiqueStorageCabinetSet: "FurnitureSet_22",
  MegaSphere: "Special_PalSphere_Grade_02",
  SphereWorkbench: "Special_SphereFactory_Black_Grade_01",
  AverageFeedBag: "AutoMealPouch_Tier2",
  WallTorch: "WallTorch",
  UnivoltSaddle: "SkillUnlock_Kirin",
  PalEssenceCondenser: "Special_PalRankUp",
  FauxCrimsonFoliageSet: "FurnitureTree_Red",
  AntiqueDeskSet: "FurnitureSet_24",
  BeginnerFishingSet: "FishingSet1",
  WheatPlantation: "Product_Farm_wheat",
  Mill: "FlourMill",
  WoodenBoard: "Processed_Wood",
  ViewingCage: "DisplayCharacter",
  ArsoxSaddle: "SkillUnlock_FlameBuffalo",
  NitewingSaddle: "SkillUnlock_HawkBird",
  HipLantern: "Lantern",
  MegaShield: "Shield_02",
  HeatResistantPeltArmor: "Battle_Armor_Grade_02_Fur_Heat",
  SurfentSaddle: "SkillUnlock_Serpent",
  LockpickingToolV1: "Unlock_Picking_Tier1",
  FauxGoldenFoliageSet: "FurnitureTree_Yellow",
  AntiqueBathSet: "FurnitureSet_20",
  AntiqueMirrorSet: "FurnitureSet_16",
  PrimitiveSword: "BronzeSword",
  CookingPot: "Product_Cooking_Grade_02",
  Heater: "Heater",
  Tombstone: "Headstone",
  PengulletRocketLauncher: "SkillUnlock_Penguin",
  GrapplingGun2: "GrapplingGun2",
  PianoFurnitureSet: "FurnitureSet_15",
  MetalShelfSet: "FurnitureSet_30",
  MegaGlider: "Battle_Glider_Grade_02",
  ColdResistantPeltArmor: "Battle_Armor_Grade_02_Fur_Cold",
  Cooler: "Cooler",
  TocotocoSGloves: "SkillUnlock_ColorfulBird",
  PengulletLuxSRocketLauncher: "SkillUnlock_Penguin_Electric",
  RingOfMercy: "Accessory_Nonkilling",
  BathroomSet: "FurnitureSet_25",
  AntiqueHighQualityFurnitureSet: "FurnitureSet_32",
  BreedingFarm: "BreedFarm",
  PalLaborResearchLab: "Lab",
  HeavyWeightModule: "SphereModule_Heavy",
  Cement: "Cement",
  StoneStructureSet: "Stone_houseset",
  StoneDefensiveWall: "DefenseWall",
  StoneGate: "Stone_Gate",
  GrintaleSaddle: "SkillUnlock_NaughtyCat",
  GigaSphere: "Special_PalSphere_Grade_03",
  WeaponWorkbench: "Product_WeaponFactory_Dirty_Grade_01",
  LargeToolbox: "ToolBoxV1",
  FreePalAllianceFlagSet: "BelieverFlagSet",
  ElphidranSaddle: "SkillUnlock_FairyDragon",
  TarantrissSaddle: "SkillUnlock_PurpleSpider",
  SweepaSaddle: "SkillUnlock_MopKing",
  DimensionalPalStorage: "DimensionPalStorage",
  AntiqueCouchSet: "FurnitureSet_18",
  Musket: "Musket",
  Gunpowder: "Battle_GunPowder_Grade_02",
  CoarseAmmo: "RoughBullet",
  TomatoPlantation: "Product_Farm_tomato",
  FlameCauldron: "OlympicCauldron",
  BearTrapLarge: "Trap_LegHold_Big",
  VanwyrmSaddle: "SkillUnlock_BirdDragon",
  EikthyrdeerTerraSaddle: "SkillUnlock_Deer_Ground",
  AntiqueDresser: "TableDresser01_Stone",
  PalExpeditionStation: "Expedition",
  StunBaton: "ElecBaton",
  HighQualityBait: "FishingBait_2",
  FleaMarketItems: "ItemBooth",
  FleaMarketPals: "PalBooth",
  VanwyrmCrystSaddle: "SkillUnlock_BirdDragon_Ice",
  HomewardThundercloud: "Homeward",
  ClockSet: "FurnitureSet_23",
  MetalChairAndDeskSet: "FurnitureSet_13",
  MetalArmor: "Battle_Armor_Grade_03_Copper",
  MetalHelm: "Battle_Helm_Grade_03_Copper",
  CurveModule: "SphereModule_Curve",
  LargeFeedBag: "AutoMealPouch_Tier3",
  WaterFountain: "Fountain",
  KingpacaSaddle: "SkillUnlock_KingAlpaca",
  FauxBambooSet: "FurnitureTree_Bamboo",
  StorageContainerSet: "FurnitureSet_6",
  MakeshiftHandgun: "MakeshiftHandgun",
  FluffyPalBed: "Infra_PalBed_Grade_02",
  MedicineRack: "PalMedicineBox",
  Clinic: "Clinic",
  FlowerBed: "FlowerBed",
  FoxparksCrystSHarness: "SkillUnlock_Kitsunebi_Ice",
  AzurobeSaddle: "SkillUnlock_BlueDragon",
  DinossomSaddle: "SkillUnlock_FlowerDinosaur",
  OreMiningSite: "Product_CopperPit",
  BoostGun: "PalDopingShot",
  BoostGunAmmo: "PalDopingShotBullet",
  HeatResistantMetalArmor: "Battle_Armor_Grade_03_Copper_Heat",
  LettucePlantation: "Product_Farm_Lettuce",
  Silo: "Silo",
  FragGrenade: "FragGrenade",
  SurfentTerraSaddle: "SkillUnlock_Serpent_Ground",
  HelzephyrSaddle: "SkillUnlock_HadesBird",
  LockpickingToolV2: "Unlock_Picking_Tier2",
  MakeshiftSMG: "MakeshiftSubmachineGun",
  PowerGenerator: "Infra_ElectricGenerator_Grade_01",
  Lamp: "Lamp",
  HumanPoweredGenerator: "ManualElectricGenerator",
  MountedCrossbow: "Battle_Defense_BowGun",
  FenglopeSaddle: "SkillUnlock_FengyunDeeper",
  PolapupSaddle: "SkillUnlock_IceSeal",
  SingleShotSphereLauncher: "Battle_RangeWeapon_SphereLauncher_Once",
  AntiqueLampSet: "FurnitureSet_29",
  HyperSphere: "Special_PalSphere_Grade_04",
  SphereAssemblyLine: "Special_SphereFactory_Black_Grade_02",
  ColdResistantMetalArmor: "Battle_Armor_Grade_03_Copper_Cold",
  SmallPouch: "AdditionalInventory_001",
  CeilingLamp: "CeilingLamp",
  ShockGrenade: "FragGrenade_Elec",
  ExtraWeaponHolster: "UnlockEquipmentSlot_Weapon_01",
  AzurobeCrystSaddle: "SkillUnlock_BlueDragon_Ice",
  FauxTropicalGreenerySet: "FurnitureTree_Tropical",
  Handgun: "Battle_RangeWeapon_HandGun",
  HandgunAmmo: "HandgunBullet",
  FineBed: "Infra_PlayerBed_Grade_02",
  HighQualityMonitoringStand: "BaseCampWorkHard02",
  StumpAndAxe: "Stump",
  BrothersOfTheEternalPyreFlagSet: "FireCultFlagSet",
  DazemuSaddle: "SkillUnlock_FeatherOstrich",
  MammorestSaddle: "SkillUnlock_GrassMammoth",
  AntiGravityBelt: "Accessory_JumpPower_Increase",
  GigaShield: "Shield_03",
  Sword: "Battle_MeleeWeapon_Sword",
  IntermediateFishingRodCattiva: "FishingRod_02_1",
  ProductionAssemblyLine: "Product_Factory_Hard_Grade_02",
  PotatoPlantation: "Product_Farm_Potato",
  IceGrenade: "FragGrenade_Ice",
  PyrinSaddle: "SkillUnlock_FireKirin",
  BeakonSaddle: "SkillUnlock_ThunderBird",
  EnhancedHipLantern: "Lantern_High",
  MakeshiftShotgun: "MakeshiftShotgun",
  Mine: "Trap_MineAttack",
  MetalStructureSet: "Metal_houseset",
  MetalDefensiveWall: "DefenseWall_Metal",
  IronGate: "Metal_Gate",
  MiningCart: "MiningTool",
  MushroomCake: "Cake02",
  RayhoundSaddle: "SkillUnlock_ThunderDog",
  Meowmere: "YakushimaBlade",
  MakeshiftAssaultRifle: "MakeshiftAssaultRifle",
  SniperModule: "SphereModule_Sniper",
  CryogenicCoolant: "Bio_Coolant",
  FishingPond: "FishingPond1",
  HighQualityHotSpring: "Spa2",
  GrapplingGun3: "GrapplingGun3",
  IncendiaryGrenade: "FragGrenade_Fire",
  GhanglerSaddle: "SkillUnlock_GhostAnglerfish",
  ReindrixSaddle: "SkillUnlock_IceDeer",
  ULTRAKILLCollabSet1: "OctaviaSet01",
  WeaponAssemblyLine: "Product_WeaponFactory_Dirty_Grade_02",
  PalRecoveryGrenade: "PalHealingGrenade",
  CarrotPlantation: "Product_Farm_Carrot",
  WitchCauldron: "Cauldron",
  PalboxControlDevice: "BaseCampWorkerExtraStation",
  ElphidranAquaSaddle: "SkillUnlock_FairyDragon_Water",
  MossandaSGrenadeLauncher: "SkillUnlock_GrassPanda",
  RayhoundCrystSaddle: "SkillUnlock_Thunderdog_Ice",
  SummoningAltar: "Altar",
  OldRevolver: "Battle_RangeWeapon_OldRevolver",
  Polymer: "Polymer",
  ElectricMine: "Trap_MineElecShock",
  WaterGrenade: "FragGrenade_Water",
  Snowman: "Snowman",
  BlazehowlSaddle: "SkillUnlock_Manticore",
  RagnahawkSaddle: "SkillUnlock_RedArmorBird",
  BroncherrySaddle: "SkillUnlock_SakuraSaurus",
  AbilityGlasses: "Accessory_TalentChecker",
  ImprovedFurnace: "Product_Ingot_Grade_02_Iron",
  RefinedMetalAxe: "Product_Axe_Grade_03",
  RefinedMetalPickaxe: "Product_Pickaxe_Grade_03",
  RefinedMetalSpear: "Spear_3",
  PyrinNoctSaddle: "SkillUnlock_FireKirin_Dark",
  MossandaLuxSGrenadeLauncher: "SkillUnlock_GrassPanda_Electric",
  DinossomLuxSaddle: "SkillUnlock_FlowerDinosaur_Electric",
  MetalBarrelSet: "FurnitureSet_5",
  AirDashBoots: "Accessory_AirDash1",
  UltraSphere: "Special_PalSphere_Grade_05",
  SphereAssemblyLineII: "Special_SphereFactory_Black_Grade_03",
  CircuitBoard: "Infra_ElectronicCircuit",
  CarbonFiber: "CarbonFiber",
  GrassGrenade: "FragGrenade_Leaf",
  BlazehowlNoctSaddle: "SkillUnlock_Manticore_Dark",
  PalumbaSaddle: "SkillUnlock_TropicalOstrich",
  IronwoodTableSet: "FurnitureSet_14",
  SingleShotRifle: "Battle_RangeWeapon_Rifle",
  RifleAmmo: "RifleBullet",
  OnionPlantation: "Product_Farm_Onion",
  HighQualityCloth: "Cloth2",
  LargePalBed: "MedicalPalBed_04",
  HugeFeedBag: "AutoMealPouch_Tier4",
  BralohaSaddle: "SkillUnlock_Plesiosaur",
  ElectricEggIncubator: "Special_ElectricHatchingPalEgg",
  MoldronSaddle: "SkillUnlock_VolcanoDragon",
  SMG: "Battle_RangeWeapon_SubmachineGun",
  RefinedMetalArmor: "Battle_Armor_Grade_03_Iron",
  RefinedMetalHelm: "Battle_Helm_Grade_04_Iron",
  CorrosiveSolvent: "Corrosive_Solvent",
  Accumulator: "EnergyStorage_Electric",
  MaraithSaddle: "SkillUnlock_GhostBeast",
  CoalQuarry: "Product_CoalPit",
  FauxDesertGreenerySet: "FurnitureTree_Desert",
  OutdoorFurnitureSet: "FurnitureSet_31",
  PalSurgeryTable: "OperatingTable",
  ScatterSphereLauncher: "Battle_RangeWeapon_SphereLauncher",
  MeteorLauncher: "Launcher_Meteor",
  DeluxeBait: "FishingBait_3",
  Refrigerator: "Refrigerator",
  IceMine: "Trap_MineFreeze",
  GroundGrenade: "FragGrenade_Ground",
  QuivernSaddle: "SkillUnlock_SkyDragon",
  LeatherChairSet: "FurnitureSet_7",
  PIDFFlagSet: "PoliceFlagSet",
  OreMiningSiteII: "Product_CopperPit_2",
  DoubleBarreledShotgun: "Battle_RangeWeapon_ShotGun",
  ShotgunShell: "ShotGunBullet",
  SliderModule: "SphereModule_Curve2",
  RefinedMetalChest: "Infra_ItemChest_Grade_03",
  AstegonSaddle: "SkillUnlock_BlackMetalDragon",
  ShroomerSaddle: "SkillUnlock_MushroomDragon",
  ShroomerNoctSaddle: "SkillUnlock_MushroomDragon_Dark",
  MetalBat: "Bat3",
  DoubleJumpBoots: "Accessory_JumpCount_Increase1",
  HeatResistantRefinedMetalArmor: "Battle_Armor_Grade_03_Iron_Heat",
  GigaGlider: "Battle_Glider_Grade_03",
  MountedMachineGun: "Battle_Defense_MachineGun",
  DarkGrenade: "FragGrenade_Dark",
  JormuntideSaddle: "SkillUnlock_Umihebi",
  GrizzboltSMinigun: "SkillUnlock_ElecPanda",
  ChilletIgnisSaddle: "SkillUnlock_WeaselDragon_Fire",
  GuildChest: "GuildChest",
  SemiAutoRifle: "Battle_RangeWeapon_SemiAutoRifle",
  ColdResistantRefinedMetalArmor: "Battle_Armor_Grade_03_Iron_Cold",
  ElectricKitchen: "Product_Cooking_Grade_03",
  AlphaWaveGenerator: "SanityDecrease1",
  ElectricHeater: "ElectricHeater",
  XenogardSaddle: "SkillUnlock_WhiteAlienDragon",
  YakumoSaddle: "SkillUnlock_GuardianDog",
  MammorestCrystSaddle: "SkillUnlock_GrassMammoth_Ice",
  CompoundBow: "Battle_RangeWeapon_CompoundBow",
  ReinforcedArrow: "ReinforcedArrow",
  ProductionAssemblyLineII: "Product_Factory_Hard_Grade_03",
  ElectricCooler: "ElectricCooler",
  DragonGrenade: "FragGrenade_Dragon",
  WhalaskaSaddle: "SkillUnlock_IceNarwhal",
  GhanglerIgnisSaddle: "SkillUnlock_GhostAnglerfish_Fire",
  ReptyroSaddle: "SkillUnlock_VolcanicMonster",
  PumpActionShotgun: "Battle_RangeWeapon_ShotGun_Multi",
  HyperShield: "Shield_04",
  MediumPouch: "AdditionalInventory_002",
  HighQualityWoodenBoard: "HighGrade_Processed_Wood",
  ElectricMedicineWorkbench: "Product_Medicine_Grade_02",
  SuzakuSaddle: "SkillUnlock_Suzaku",
  ReptyroCrystSaddle: "SkillUnlock_VolcanicMonster_Ice",
  LoggingSiteII: "Product_StationDeforest2",
  LegendarySphere: "Special_PalSphere_Grade_06",
  ElectricFurnace: "Product_Ingot_Grade_03_Steal",
  BioBattery: "Bio_Battery",
  Katana: "Katana",
  PalMetalPickaxe: "Battle_MeleeWeapon_Pickaxe_Steal",
  PalMetalAxe: "Battle_MeleeWeapon_Axe_Steal",
  SuzakuAquaSaddle: "SkillUnlock_Suzaku_Water",
  BroncherryAquaSaddle: "SkillUnlock_SakuraSaurus_Water",
  GlassStructureSet: "Glass_houseset",
  DecalGunSet: "DecalGunSet",
  AssaultRifle: "Battle_RangeWeapon_AssaultRifle",
  AssaultRifleAmmo: "AssaultRifleBullet",
  AdvancedFishingRodPengullet: "FishingRod_03_1",
  DraftingTable: "CompositeDesk",
  QuivernBotanSaddle: "SkillUnlock_SkyDragon_Grass",
  RelaxaurusMissileLauncher: "SkillUnlock_LazyDragon",
  WumpoSaddle: "SkillUnlock_Yeti",
  SulfurQuarry: "Product_SulfurPit",
  PalMetalArmor: "Battle_Armor_Grade_04_Steal",
  PalMetalHelm: "Battle_Helm_Grade_05_Steal",
  BetaWaveGenerator: "WorkSpeedIncrease1",
  LargeMountedLamp: "LargeLamp",
  BlazamutSaddle: "SkillUnlock_KingBahamut",
  KingpacaCrystSaddle: "SkillUnlock_KingAlpaca_Ice",
  StreetLampSet: "FurnitureSet_27",
  AmusementFurnitureSet: "FurnitureSet_26",
  SemiAutoShotgun: "Battle_RangeWeapon_SemiAutoShotgun",
  WeaponAssemblyLineII: "Product_WeaponFactory_Dirty_Grade_03",
  VegetableCake: "Cake03",
  GiantFeedBag: "AutoMealPouch_Tier5",
  LargeCeilingLamp: "LargeCeilingLamp",
  HelzephyrLuxSaddle: "SkillUnlock_HadesBird_Electric",
  ShadowbeakSaddle: "SkillUnlock_BlackGriffon",
  EmergencyExitSignSet: "FurnitureSet_8",
  LargeIncubator: "MultiHatchingPalEgg",
  HeatResistantPalMetalArmor: "Battle_Armor_Grade_04_Steal_Heat",
  SniperModuleII: "SphereModule_Sniper2",
  ElectricPylon: "TransmissionTower",
  RelaxaurusLuxSMissileLauncher: "SkillUnlock_LazyDragon_Electric",
  DualithSaddle: "SkillUnlock_GrassGolem",
  TetroiseSaddle: "SkillUnlock_CubeTurtle",
  TrafficControlSet: "FurnitureSet_11",
  GrapplingGun4: "GrapplingGun4",
  ItemRetrievalMachine: "BaseCampItemDispenser",
  LargeScaleStoneOven: "HugeKitchen",
  JapaneseStyleStructureSet: "JapaneseStyle_houseset",
  FauxSnowyGreenerySet: "FurnitureTree_Snow",
  RoadSignSet: "FurnitureSet_12",
  BarricadeSet: "FurnitureSet_10",
  LargePowerGenerator: "ElectricGenerator_Large",
  ColdResistantPalMetalArmor: "Battle_Armor_Grade_04_Steal_Cold",
  CrudeOilExtractor: "OilPump",
  Plasteel: "Plastic",
  Computer: "Computer",
  MountedMissileLauncher: "Battle_Defense_Missile",
  PALGeneticResearchUnitFlagSet: "ScientistFlagSet",
  HighPressureCrudeOilExtractor: "OilPump02",
  UltimateSphere: "Special_PalSphere_Grade_07",
  PlasteelArmor: "Battle_Armor_Grade_05_Plastic",
  PlasteelHelmet: "Battle_Helm_Grade_06_Plastic",
  LaserRifle: "Battle_RangeWeapon_LaserRifle",
  EnergyCartridge: "LaserBullet",
  ColdFoodBox: "CoolerPalFoodBox",
  WumpoBotanSaddle: "SkillUnlock_Yeti_Grass",
  GliderTera: "Battle_Glider_Grade_04",
  Flamethrower: "Battle_RangeWeapon_FlameThrower",
  FlamethrowerFuel: "FlamethrowerBullet",
  AlluringBait: "FishingBait_3_A",
  NyafiaSShotgun: "SkillUnlock_BadCatgirl",
  PureQuartzQuarry: "Product_QuartzPit",
  LargePouch: "AdditionalInventory_003",
  HeatResistantPlasteelArmor: "Battle_Armor_Grade_05_Plastic_Heat",
  GrenadeLauncher: "Battle_RangeWeapon_GrenadeLauncher",
  GrenadeAmmo: "GrenadeBullet",
  FragGrenadeMk2: "FragGrenade_Super",
  SelyneSaddle: "SkillUnlock_MoonQueen",
  LockpickingToolV3: "Unlock_Picking_Tier3",
  BulldosuSaddle: "SkillUnlock_SumoDog",
  PlasmaMulticutter: "LaserMiningTool",
  ColdResistantPlasteelArmor: "Battle_Armor_Grade_05_Plastic_Cold",
  GatlingGun: "Battle_RangeWeapon_GatlingGun",
  GatlingGunAmmo: "GatlingBullet",
  CryogenicCrusher: "IceCrusher",
  ExtraWeaponHolster2: "UnlockEquipmentSlot_Weapon_02",
  GildaneSaddle: "SkillUnlock_GoldenHorse",
  CelesdirSaddle: "SkillUnlock_WhiteDeer",
  LilySSpear: "Spear_ForestBoss",
  ShieldUltra: "Shield_05",
  LightweightPlasteelArmor: "Battle_Armor_Grade_05_Plastic_Weight",
  PolapupTerraSaddle: "SkillUnlock_IceSeal_Ground",
  BlazamutRyuSaddle: "SkillUnlock_KingBahamut_Dragon",
  JapaneseStyleFurnitureSet: "FurnitureSet_Japanese",
  MoonflowerFlagSet: "NinjaFlagSet",
  HomingSphereLauncher: "Battle_RangeWeapon_HomingSphereLauncher",
  GuidedMissileLauncher: "Battle_RangeWeapon_GuidedMissileLauncher",
  MissileAmmo: "MissileBullet",
  PalDisassemblyConveyor: "DismantlingConveyor",
  PalPod: "MedicalPalBed_05",
  ULTRAKILLCollabSet2: "OctaviaSet02",
  FauxCherryBlossomsSet: "FurnitureTree_Cherry",
  AdvancedBow: "SFBow",
  AdvancedArrow: "SFArrow",
  GiantPouch: "AdditionalInventory_004",
  BeamSword: "BeamSword",
  StarryonSaddle: "SkillUnlock_NightBlueHorse",
  FenglopeLuxSaddle: "SkillUnlock_FengyunDeeper_Electric",
  KitsunSaddle: "SkillUnlock_AmaterasuWolf",
  ExoticSphere: "PalSphere_Exotic",
  AdvancedSphereAssemblyLine: "SphereFactory_Black_04",
  Hexolite: "StainlessSteel",
  GiganticFurnace: "BlastFurnace4",
  MetalDetector: "MetalDetector",
  SmokieSHarness: "SkillUnlock_BlackPuppy",
  AzurmaneSaddle: "SkillUnlock_BlueThunderHorse",
  LargeScaleElectricEggIncubator: "MultiElectricHatchingPalEgg",
  AdvancedChest: "ItemChest_04",
  LaserGatlingGun: "LaserGatlingGun",
  LaserGatlingCartridge: "LaserGatlingBullet",
  HexoliteArmor: "SFArmor",
  ThermalCore: "Thermal_Core",
  JormuntideIgnisSaddle: "SkillUnlock_Umihebi_Fire",
  KitsunNoctSaddle: "SkillUnlock_AmaterasuWolf_Dark",
  AdvancedShield: "Shield_SF",
  HexoliteHelmet: "SFHelmet",
  ExtravagantVegetableCake: "Cake04",
  FeybreakFlagSet: "DarkIslandFlagSet",
  FalerisSaddle: "SkillUnlock_Horus",
  FalerisAquaSaddle: "SkillUnlock_Horus_Water",
  SilvegisSaddle: "SkillUnlock_WhiteShieldDragon",
  PlasmaCannon: "EnergyRocketLauncher",
  PlasmaCartridge: "EnergyLauncherBullet",
  AdvancedRecoveryMeds: "Potion_Extreme",
  RevivalPotion: "PalRevive",
  AdvancedMedicineWorkbench: "MedicineFacility_03",
  PaladiusSaddle: "SkillUnlock_SaintCentaur",
  NecromusSaddle: "SkillUnlock_BlackCentaur",
  DoubleAirDashBoots: "Accessory_AirDash2",
  PowerfulFishingMagnet: "Salvage_TreasureBoxKey02",
  CoralumIngot: "ManganeseIngot",
  AdvancedWorkshop: "Factory_Hard_04",
  FuturisticStructureSet: "SF_houseset",
  HexoliteQuartzMine: "CrystalPit",
  FrostallionSaddle: "SkillUnlock_IceHorse",
  FrostallionNoctSaddle: "SkillUnlock_IceHorse_Dark",
  EnergyShotgun: "EnergyShotgun",
  EnergyShotgunAmmo: "EnergyShotgunBullet",
  AdvancedWeaponAssemblyLine: "WeaponFactory_Dirty_04",
  HeatResistantHexoliteArmor: "SFArmorHeat",
  MegaboostGun: "PalDopingShot_2",
  GrapplingGun5: "GrapplingGun5",
  OverheatRifle: "OverheatRifle",
  OverheatRifleAmmo: "OverheatRifleBullet",
  ColdResistantHexoliteArmor: "SFArmorCold",
  JapaneseStyleHotSpring: "Spa3",
  UnivoltCrystSaddle: "SkillUnlock_Kirin_Ice",
  NeptiliusSaddle: "SkillUnlock_PoseidonOrca",
  FrostallionStatue: "IceHorseStatue",
  RocketLauncher: "Battle_RangeWeapon_RocketLauncher",
  RocketAmmo: "LauncherBullet",
  ChargeRifle: "ChargeLaserRifle",
  ChargeRifleAmmo: "ChargeLaserRifleBullet",
  LightweightHexoliteArmor: "SFArmorWeight",
  SolmoraSaddle: "SkillUnlock_KingSunfish",
  TripleAirDashBoots: "Accessory_AirDash3",
  AncientFurnace: "AncientBlastFurnace",
  SoraliteIngot: "SkyislandIngot",
  AquaticConstructionKit: "WaterBuildKit",
  SolmoraLuxSaddle: "SkillUnlock_KingSunfish_Thunder",
  DynamoffSaddle: "SkillUnlock_ThunderFluffyBird",
  XenolordSaddle: "SkillUnlock_DarkMechaDragon",
  SolSphere: "PalSphere_Ancient_1",
  MechanicalBow: "SkyBow",
  MechanicalBowAmmo: "SkyBowArrow",
  AICore: "AIcore",
  AncientWorkbench: "AncientWorkBench",
  AncientStructureSet: "Ancient_Houseset",
  EnhancedLilySSpear: "Spear_ForestBoss2",
  CombatSMG: "SkySubmachineGun",
  CombatSMGAmmo: "SkySubmachineGunBullet",
  AncientArmor: "AncientArmor",
  AncientHelm: "AncientHelmet",
  EidrolonSaddle: "SkillUnlock_GhostDragon",
  PrototypeShotgun: "SkyShotgun",
  PrototypeShotgunAmmo: "SkyShotgunBullet",
  HomingModule: "SphereModule_Homing",
  LargeFishingPond: "FishingPond2",
  DualithNoctSaddle: "SkillUnlock_GrassGolem_Dark",
  HeavyAssaultRifle: "SkyAssaultRifle",
  HeavyAssaultRifleAmmo: "SkyAssaultRifleBullet",
  AncientKitchen: "AncientCookingStove",
  HartalisSaddle: "SkillUnlock_LegendDeer",
  TripleJumpBoots: "Accessory_JumpCount_Increase2",
  MoldronCrystSaddle: "SkillUnlock_VolcanoDragon_Ice",
  AncientShield: "Shield_07",
  AncientMonitoringStand: "BaseCampWorkHard03",
  SkillfruitOrchard: "Farm_SkillFruits",
  AzureCovenantFlagSet: "SkyIslandFlagSet",
  BeakonCrystSaddle: "SkillUnlock_ThunderBird_Ice",
  WhalaskaIgnisSaddle: "SkillUnlock_IceNarwhal_Fire",
  TacticalGrenadeLauncher: "SkyGrenadeLauncher",
  TacticalGrenadeLauncherAmmo: "SkyGrenadeLauncherBullet",
  SoraliteQuarry: "SkyIslandOrePit",
  RoujaySaddle: "SkillUnlock_ThiefBird",
  OphydiaSaddle: "SkillUnlock_LotusDragon",
  LaserSword: "SkyBeamSword",
  GoldCoinAssemblyLine: "Factory_Money",
  AncientClinic: "Ancient_Clinic",
  AncientPalBed: "Ancient_MedicalPalBed",
  BastigorSHammer: "SkillUnlock_SnowTigerBeastman",
  PaloxiteIngot: "WorldTreeIngot",
  AncientSphere: "PalSphere_Ancient_2",
  AncientRelicRecycler: "AncientRelicRecycler",
  SpecialCake: "Cake05",
  BeamScatter: "WidePenetrateShotgun",
  BeamScatterAmmo: "WidePenetrateShotgunBullet",
  HeatResistantAncientArmor: "AncientArmorHeat",
  AncientPowerGenerator: "AncientElectricGenerator",
  TetroisePrimoSaddle: "SkillUnlock_CubeTurtle_Neutral",
  AncientHotSpring: "Ancient_Spa",
  AncientHatchery: "MultiElectricHatchingPalEggWithBreed",
  CorrosiveMistMask: "GasMask",
  ExplosionResistantUndershirt: "Accessory_ExplosionResist",
  EidrolonIgnisSaddle: "SkillUnlock_GhostDragon_Fire",
  DroneLauncher: "DroneLauncher",
  ColdResistantAncientArmor: "AncientArmorCold",
  StarryonPrimoSaddle: "SkillUnlock_NightBlueHorse_Neutral",
  ShaolongSaddle: "SkillUnlock_BlueSkyDragon",
  PlasmaRifle: "ElectricArcAssaultRifle",
  PlasmaRifleAmmo: "ElectricArcAssaultRifleBullet",
  AncientMaterialSynthesizer: "AncientMultiProduct",
  AncientFarm: "AncientFarmBlock",
  CelesdirNoctSaddle: "SkillUnlock_WhiteDeer_Dark",
  LightweightAncientArmor: "AncientArmorWeight",
  NutrientTonic: "Supplement",
  AegidronSaddle: "SkillUnlock_DomeArmorDragon",
  JetragonSMissileLauncher: "SkillUnlock_JetDragon",
  JetragonStatue: "JetDragonStatue",
  BeamLauncher: "BeamLauncher",
  BeamLauncherAmmo: "BeamLauncherBullet",
  WingPack: "WingGlider",
  WingCell: "WingGlider_Fuel",
} as const;

export type TechnologyId = (typeof TechnologyId)[keyof typeof TechnologyId];

export const TECHNOLOGY_ID_TO_NAME: Record<TechnologyId, string> = {
  [TechnologyId.PrimitiveWorkbench]: "Primitive Workbench",
  [TechnologyId.StoneAxe]: "Stone Axe",
  [TechnologyId.StonePickaxe]: "Stone Pickaxe",
  [TechnologyId.HandHeldTorch]: "Hand-Held Torch",
  [TechnologyId.WoodenClub]: "Wooden Club",
  [TechnologyId.Palbox]: "Palbox",
  [TechnologyId.PalSphere]: "Pal Sphere",
  [TechnologyId.Campfire]: "Campfire",
  [TechnologyId.WoodenChest]: "Wooden Chest",
  [TechnologyId.RepairBench]: "Repair Bench",
  [TechnologyId.WoodenStructureSet]: "Wooden Structure Set",
  [TechnologyId.PalDressingFacility]: "Pal Dressing Facility",
  [TechnologyId.OldBow]: "Old Bow",
  [TechnologyId.Arrow]: "Arrow",
  [TechnologyId.StoneSpear]: "Stone Spear",
  [TechnologyId.ShoddyBed]: "Shoddy Bed",
  [TechnologyId.StrawPalBed]: "Straw Pal Bed",
  [TechnologyId.GlobalPalbox]: "Global Palbox",
  [TechnologyId.CommonShield]: "Common Shield",
  [TechnologyId.ClothOutfit]: "Cloth Outfit",
  [TechnologyId.Cloth]: "Cloth",
  [TechnologyId.FeedBox]: "Feed Box",
  [TechnologyId.BerryPlantation]: "Berry Plantation",
  [TechnologyId.Ranch]: "Ranch",
  [TechnologyId.NormalParachute]: "Normal Parachute",
  [TechnologyId.WoodenLivingRoomFurnitureSet]: "Wooden Living Room Furniture Set",
  [TechnologyId.WoodenTavernFurnitureSet]: "Wooden Tavern Furniture Set",
  [TechnologyId.WoodenTavernCabinetFurnitureSet]: "Wooden Tavern Cabinet Furniture Set",
  [TechnologyId.PalGearWorkbench]: "Pal Gear Workbench",
  [TechnologyId.FireArrow]: "Fire Arrow",
  [TechnologyId.MountedTorch]: "Mounted Torch",
  [TechnologyId.Sign]: "Sign",
  [TechnologyId.WallMountedSign]: "Wall-Mounted Sign",
  [TechnologyId.RushoarSaddle]: "Rushoar Saddle",
  [TechnologyId.FoxparksHarness]: "Foxparks' Harness",
  [TechnologyId.HouseplantSet]: "Houseplant Set",
  [TechnologyId.MonitoringStand]: "Monitoring Stand",
  [TechnologyId.Bat]: "Bat",
  [TechnologyId.LoggingSite]: "Logging Site",
  [TechnologyId.StonePit]: "Stone Pit",
  [TechnologyId.Sandbag]: "Sandbag",
  [TechnologyId.AlarmBell]: "Alarm Bell",
  [TechnologyId.MelpacaSaddle]: "Melpaca Saddle",
  [TechnologyId.WallMountedHouseplantSet]: "Wall-Mounted Houseplant Set",
  [TechnologyId.Crusher]: "Crusher",
  [TechnologyId.PoisonArrow]: "Poison Arrow",
  [TechnologyId.WoodenDefensiveWall]: "Wooden Defensive Wall",
  [TechnologyId.WoodenGate]: "Wooden Gate",
  [TechnologyId.HangingTrap]: "Hanging Trap",
  [TechnologyId.FireplaceSet]: "Fireplace Set",
  [TechnologyId.StatueOfPower]: "Statue of Power",
  [TechnologyId.SmallFeedBag]: "Small Feed Bag",
  [TechnologyId.TropicalOutfit]: "Tropical Outfit",
  [TechnologyId.TundraOutfit]: "Tundra Outfit",
  [TechnologyId.HotSpring]: "Hot Spring",
  [TechnologyId.DirehowlSSaddledHarness]: "Direhowl's Saddled Harness",
  [TechnologyId.CarpetSet]: "Carpet Set",
  [TechnologyId.PrimitiveFurnace]: "Primitive Furnace",
  [TechnologyId.ThreeShotBow]: "Three Shot Bow",
  [TechnologyId.FeatheredHairBand]: "Feathered Hair Band",
  [TechnologyId.Nail]: "Nail",
  [TechnologyId.Ladder]: "Ladder",
  [TechnologyId.BearTrapSmall]: "Bear Trap (Small)",
  [TechnologyId.EggIncubator]: "Egg Incubator",
  [TechnologyId.AntiqueStorageSet]: "Antique Storage Set",
  [TechnologyId.MetalAxe]: "Metal Axe",
  [TechnologyId.MetalPickaxe]: "Metal Pickaxe",
  [TechnologyId.HighQualityWorkbench]: "High-Quality Workbench",
  [TechnologyId.RayneSyndicateFlagSet]: "Rayne Syndicate Flag Set",
  [TechnologyId.ChilletSaddle]: "Chillet Saddle",
  [TechnologyId.LifmunkSSubmachineGun]: "Lifmunk's Submachine Gun",
  [TechnologyId.AntiqueChairSet]: "Antique Chair Set",
  [TechnologyId.PeltArmor]: "Pelt Armor",
  [TechnologyId.MeatCleaver]: "Meat Cleaver",
  [TechnologyId.MedievalMedicineWorkbench]: "Medieval Medicine Workbench",
  [TechnologyId.TanzeeSAssaultRifle]: "Tanzee's Assault Rifle",
  [TechnologyId.EikthyrdeerSaddle]: "Eikthyrdeer Saddle",
  [TechnologyId.GrapplingGun]: "GrapplingGun",
  [TechnologyId.FauxGreenerySet]: "Faux Greenery Set",
  [TechnologyId.TidyTableSet]: "Tidy Table Set",
  [TechnologyId.Crossbow]: "Crossbow",
  [TechnologyId.MetalSpear]: "Metal Spear",
  [TechnologyId.MetalChest]: "Metal Chest",
  [TechnologyId.CoolerBox]: "Cooler Box",
  [TechnologyId.TrainingDummy]: "Training Dummy",
  [TechnologyId.TanzeeIgnisSAssaultRifle]: "Tanzee Ignis's Assault Rifle",
  [TechnologyId.AntiqueStorageCabinetSet]: "Antique Storage Cabinet Set",
  [TechnologyId.MegaSphere]: "Mega Sphere",
  [TechnologyId.SphereWorkbench]: "Sphere Workbench",
  [TechnologyId.AverageFeedBag]: "Average Feed Bag",
  [TechnologyId.WallTorch]: "Wall Torch",
  [TechnologyId.UnivoltSaddle]: "Univolt Saddle",
  [TechnologyId.PalEssenceCondenser]: "Pal Essence Condenser",
  [TechnologyId.FauxCrimsonFoliageSet]: "Faux Crimson Foliage Set",
  [TechnologyId.AntiqueDeskSet]: "Antique Desk Set",
  [TechnologyId.BeginnerFishingSet]: "Beginner Fishing Set",
  [TechnologyId.WheatPlantation]: "Wheat Plantation",
  [TechnologyId.Mill]: "Mill",
  [TechnologyId.WoodenBoard]: "Wooden Board",
  [TechnologyId.ViewingCage]: "Viewing Cage",
  [TechnologyId.ArsoxSaddle]: "Arsox Saddle",
  [TechnologyId.NitewingSaddle]: "Nitewing Saddle",
  [TechnologyId.HipLantern]: "Hip Lantern",
  [TechnologyId.MegaShield]: "Mega Shield",
  [TechnologyId.HeatResistantPeltArmor]: "Heat Resistant Pelt Armor",
  [TechnologyId.SurfentSaddle]: "Surfent Saddle",
  [TechnologyId.LockpickingToolV1]: "Lockpicking Tool v1",
  [TechnologyId.FauxGoldenFoliageSet]: "Faux Golden Foliage Set",
  [TechnologyId.AntiqueBathSet]: "Antique Bath Set",
  [TechnologyId.AntiqueMirrorSet]: "Antique Mirror Set",
  [TechnologyId.PrimitiveSword]: "Primitive Sword",
  [TechnologyId.CookingPot]: "Cooking Pot",
  [TechnologyId.Heater]: "Heater",
  [TechnologyId.Tombstone]: "Tombstone",
  [TechnologyId.PengulletRocketLauncher]: "Pengullet Rocket Launcher",
  [TechnologyId.GrapplingGun2]: "GrapplingGun2",
  [TechnologyId.PianoFurnitureSet]: "Piano Furniture Set",
  [TechnologyId.MetalShelfSet]: "Metal Shelf Set",
  [TechnologyId.MegaGlider]: "Mega Glider",
  [TechnologyId.ColdResistantPeltArmor]: "Cold Resistant Pelt Armor",
  [TechnologyId.Cooler]: "Cooler",
  [TechnologyId.TocotocoSGloves]: "Tocotoco's Gloves",
  [TechnologyId.PengulletLuxSRocketLauncher]: "Pengullet Lux's Rocket Launcher",
  [TechnologyId.RingOfMercy]: "Ring of Mercy",
  [TechnologyId.BathroomSet]: "Bathroom Set",
  [TechnologyId.AntiqueHighQualityFurnitureSet]: "Antique High Quality Furniture Set",
  [TechnologyId.BreedingFarm]: "Breeding Farm",
  [TechnologyId.PalLaborResearchLab]: "Pal Labor Research Lab",
  [TechnologyId.HeavyWeightModule]: "Heavy Weight Module",
  [TechnologyId.Cement]: "Cement",
  [TechnologyId.StoneStructureSet]: "Stone Structure Set",
  [TechnologyId.StoneDefensiveWall]: "Stone Defensive Wall",
  [TechnologyId.StoneGate]: "Stone Gate",
  [TechnologyId.GrintaleSaddle]: "Grintale Saddle",
  [TechnologyId.GigaSphere]: "Giga Sphere",
  [TechnologyId.WeaponWorkbench]: "Weapon Workbench",
  [TechnologyId.LargeToolbox]: "Large Toolbox",
  [TechnologyId.FreePalAllianceFlagSet]: "Free Pal Alliance Flag Set",
  [TechnologyId.ElphidranSaddle]: "Elphidran Saddle",
  [TechnologyId.TarantrissSaddle]: "Tarantriss Saddle",
  [TechnologyId.SweepaSaddle]: "Sweepa Saddle",
  [TechnologyId.DimensionalPalStorage]: "Dimensional Pal Storage",
  [TechnologyId.AntiqueCouchSet]: "Antique Couch Set",
  [TechnologyId.Musket]: "Musket",
  [TechnologyId.Gunpowder]: "Gunpowder",
  [TechnologyId.CoarseAmmo]: "Coarse Ammo",
  [TechnologyId.TomatoPlantation]: "Tomato Plantation",
  [TechnologyId.FlameCauldron]: "Flame Cauldron",
  [TechnologyId.BearTrapLarge]: "Bear Trap (Large)",
  [TechnologyId.VanwyrmSaddle]: "Vanwyrm Saddle",
  [TechnologyId.EikthyrdeerTerraSaddle]: "Eikthyrdeer Terra Saddle",
  [TechnologyId.AntiqueDresser]: "Antique Dresser",
  [TechnologyId.PalExpeditionStation]: "Pal Expedition Station",
  [TechnologyId.StunBaton]: "Stun Baton",
  [TechnologyId.HighQualityBait]: "High Quality Bait",
  [TechnologyId.FleaMarketItems]: "Flea Market (Items)",
  [TechnologyId.FleaMarketPals]: "Flea Market (Pals)",
  [TechnologyId.VanwyrmCrystSaddle]: "Vanwyrm Cryst Saddle",
  [TechnologyId.HomewardThundercloud]: "Homeward Thundercloud",
  [TechnologyId.ClockSet]: "Clock Set",
  [TechnologyId.MetalChairAndDeskSet]: "Metal Chair and Desk Set",
  [TechnologyId.MetalArmor]: "Metal Armor",
  [TechnologyId.MetalHelm]: "Metal Helm",
  [TechnologyId.CurveModule]: "Curve Module",
  [TechnologyId.LargeFeedBag]: "Large Feed Bag",
  [TechnologyId.WaterFountain]: "Water Fountain",
  [TechnologyId.KingpacaSaddle]: "Kingpaca Saddle",
  [TechnologyId.FauxBambooSet]: "Faux Bamboo Set",
  [TechnologyId.StorageContainerSet]: "Storage Container Set",
  [TechnologyId.MakeshiftHandgun]: "Makeshift Handgun",
  [TechnologyId.FluffyPalBed]: "Fluffy Pal Bed",
  [TechnologyId.MedicineRack]: "Medicine Rack",
  [TechnologyId.Clinic]: "Clinic",
  [TechnologyId.FlowerBed]: "Flower Bed",
  [TechnologyId.FoxparksCrystSHarness]: "Foxparks Cryst's Harness",
  [TechnologyId.AzurobeSaddle]: "Azurobe Saddle",
  [TechnologyId.DinossomSaddle]: "Dinossom Saddle",
  [TechnologyId.OreMiningSite]: "Ore Mining Site",
  [TechnologyId.BoostGun]: "Boost Gun",
  [TechnologyId.BoostGunAmmo]: "Boost Gun Ammo",
  [TechnologyId.HeatResistantMetalArmor]: "Heat Resistant Metal Armor",
  [TechnologyId.LettucePlantation]: "Lettuce Plantation",
  [TechnologyId.Silo]: "Silo",
  [TechnologyId.FragGrenade]: "Frag Grenade",
  [TechnologyId.SurfentTerraSaddle]: "Surfent Terra Saddle",
  [TechnologyId.HelzephyrSaddle]: "Helzephyr Saddle",
  [TechnologyId.LockpickingToolV2]: "Lockpicking Tool v2",
  [TechnologyId.MakeshiftSMG]: "Makeshift SMG",
  [TechnologyId.PowerGenerator]: "Power Generator",
  [TechnologyId.Lamp]: "Lamp",
  [TechnologyId.HumanPoweredGenerator]: "Human-Powered Generator",
  [TechnologyId.MountedCrossbow]: "Mounted Crossbow",
  [TechnologyId.FenglopeSaddle]: "Fenglope Saddle",
  [TechnologyId.PolapupSaddle]: "Polapup Saddle",
  [TechnologyId.SingleShotSphereLauncher]: "Single-Shot Sphere Launcher",
  [TechnologyId.AntiqueLampSet]: "Antique Lamp Set",
  [TechnologyId.HyperSphere]: "Hyper Sphere",
  [TechnologyId.SphereAssemblyLine]: "Sphere Assembly Line",
  [TechnologyId.ColdResistantMetalArmor]: "Cold Resistant Metal Armor",
  [TechnologyId.SmallPouch]: "Small Pouch",
  [TechnologyId.CeilingLamp]: "Ceiling Lamp",
  [TechnologyId.ShockGrenade]: "Shock Grenade",
  [TechnologyId.ExtraWeaponHolster]: "Extra Weapon Holster",
  [TechnologyId.AzurobeCrystSaddle]: "Azurobe Cryst Saddle",
  [TechnologyId.FauxTropicalGreenerySet]: "Faux Tropical Greenery Set",
  [TechnologyId.Handgun]: "Handgun",
  [TechnologyId.HandgunAmmo]: "Handgun Ammo",
  [TechnologyId.FineBed]: "Fine Bed",
  [TechnologyId.HighQualityMonitoringStand]: "High Quality Monitoring Stand",
  [TechnologyId.StumpAndAxe]: "Stump and Axe",
  [TechnologyId.BrothersOfTheEternalPyreFlagSet]: "Brothers of the Eternal Pyre Flag Set",
  [TechnologyId.DazemuSaddle]: "Dazemu Saddle",
  [TechnologyId.MammorestSaddle]: "Mammorest Saddle",
  [TechnologyId.AntiGravityBelt]: "Anti-Gravity Belt",
  [TechnologyId.GigaShield]: "Giga Shield",
  [TechnologyId.Sword]: "Sword",
  [TechnologyId.IntermediateFishingRodCattiva]: "Intermediate Fishing Rod (Cattiva)",
  [TechnologyId.ProductionAssemblyLine]: "Production Assembly Line",
  [TechnologyId.PotatoPlantation]: "Potato Plantation",
  [TechnologyId.IceGrenade]: "Ice Grenade",
  [TechnologyId.PyrinSaddle]: "Pyrin Saddle",
  [TechnologyId.BeakonSaddle]: "Beakon Saddle",
  [TechnologyId.EnhancedHipLantern]: "Enhanced Hip Lantern",
  [TechnologyId.MakeshiftShotgun]: "Makeshift Shotgun",
  [TechnologyId.Mine]: "Mine",
  [TechnologyId.MetalStructureSet]: "Metal Structure Set",
  [TechnologyId.MetalDefensiveWall]: "Metal Defensive Wall",
  [TechnologyId.IronGate]: "Iron Gate",
  [TechnologyId.MiningCart]: "Mining Cart",
  [TechnologyId.MushroomCake]: "Mushroom Cake",
  [TechnologyId.RayhoundSaddle]: "Rayhound Saddle",
  [TechnologyId.Meowmere]: "Meowmere",
  [TechnologyId.MakeshiftAssaultRifle]: "Makeshift Assault Rifle",
  [TechnologyId.SniperModule]: "Sniper Module",
  [TechnologyId.CryogenicCoolant]: "Cryogenic Coolant",
  [TechnologyId.FishingPond]: "Fishing Pond",
  [TechnologyId.HighQualityHotSpring]: "High Quality Hot Spring",
  [TechnologyId.GrapplingGun3]: "GrapplingGun3",
  [TechnologyId.IncendiaryGrenade]: "Incendiary Grenade",
  [TechnologyId.GhanglerSaddle]: "Ghangler Saddle",
  [TechnologyId.ReindrixSaddle]: "Reindrix Saddle",
  [TechnologyId.ULTRAKILLCollabSet1]: "ULTRAKILL Collab Set 1",
  [TechnologyId.WeaponAssemblyLine]: "Weapon Assembly Line",
  [TechnologyId.PalRecoveryGrenade]: "Pal Recovery Grenade",
  [TechnologyId.CarrotPlantation]: "Carrot Plantation",
  [TechnologyId.WitchCauldron]: "Witch Cauldron",
  [TechnologyId.PalboxControlDevice]: "Palbox Control Device",
  [TechnologyId.ElphidranAquaSaddle]: "Elphidran Aqua Saddle",
  [TechnologyId.MossandaSGrenadeLauncher]: "Mossanda's Grenade Launcher",
  [TechnologyId.RayhoundCrystSaddle]: "Rayhound Cryst Saddle",
  [TechnologyId.SummoningAltar]: "Summoning Altar",
  [TechnologyId.OldRevolver]: "Old Revolver",
  [TechnologyId.Polymer]: "Polymer",
  [TechnologyId.ElectricMine]: "Electric Mine",
  [TechnologyId.WaterGrenade]: "Water Grenade",
  [TechnologyId.Snowman]: "Snowman",
  [TechnologyId.BlazehowlSaddle]: "Blazehowl Saddle",
  [TechnologyId.RagnahawkSaddle]: "Ragnahawk Saddle",
  [TechnologyId.BroncherrySaddle]: "Broncherry Saddle",
  [TechnologyId.AbilityGlasses]: "Ability Glasses",
  [TechnologyId.ImprovedFurnace]: "Improved Furnace",
  [TechnologyId.RefinedMetalAxe]: "Refined Metal Axe",
  [TechnologyId.RefinedMetalPickaxe]: "Refined Metal Pickaxe",
  [TechnologyId.RefinedMetalSpear]: "Refined Metal Spear",
  [TechnologyId.PyrinNoctSaddle]: "Pyrin Noct Saddle",
  [TechnologyId.MossandaLuxSGrenadeLauncher]: "Mossanda Lux's Grenade Launcher",
  [TechnologyId.DinossomLuxSaddle]: "Dinossom Lux Saddle",
  [TechnologyId.MetalBarrelSet]: "Metal Barrel Set",
  [TechnologyId.AirDashBoots]: "Air Dash Boots",
  [TechnologyId.UltraSphere]: "Ultra Sphere",
  [TechnologyId.SphereAssemblyLineII]: "Sphere Assembly Line II",
  [TechnologyId.CircuitBoard]: "Circuit Board",
  [TechnologyId.CarbonFiber]: "Carbon Fiber",
  [TechnologyId.GrassGrenade]: "Grass Grenade",
  [TechnologyId.BlazehowlNoctSaddle]: "Blazehowl Noct Saddle",
  [TechnologyId.PalumbaSaddle]: "Palumba Saddle",
  [TechnologyId.IronwoodTableSet]: "Ironwood Table Set",
  [TechnologyId.SingleShotRifle]: "Single-Shot Rifle",
  [TechnologyId.RifleAmmo]: "Rifle Ammo",
  [TechnologyId.OnionPlantation]: "Onion Plantation",
  [TechnologyId.HighQualityCloth]: "High Quality Cloth",
  [TechnologyId.LargePalBed]: "Large Pal Bed",
  [TechnologyId.HugeFeedBag]: "Huge Feed Bag",
  [TechnologyId.BralohaSaddle]: "Braloha Saddle",
  [TechnologyId.ElectricEggIncubator]: "Electric Egg Incubator",
  [TechnologyId.MoldronSaddle]: "Moldron Saddle",
  [TechnologyId.SMG]: "SMG",
  [TechnologyId.RefinedMetalArmor]: "Refined Metal Armor",
  [TechnologyId.RefinedMetalHelm]: "Refined Metal Helm",
  [TechnologyId.CorrosiveSolvent]: "Corrosive Solvent",
  [TechnologyId.Accumulator]: "Accumulator",
  [TechnologyId.MaraithSaddle]: "Maraith Saddle",
  [TechnologyId.CoalQuarry]: "Coal Quarry",
  [TechnologyId.FauxDesertGreenerySet]: "Faux Desert Greenery Set",
  [TechnologyId.OutdoorFurnitureSet]: "Outdoor Furniture Set",
  [TechnologyId.PalSurgeryTable]: "Pal Surgery Table",
  [TechnologyId.ScatterSphereLauncher]: "Scatter Sphere Launcher",
  [TechnologyId.MeteorLauncher]: "Meteor Launcher",
  [TechnologyId.DeluxeBait]: "Deluxe Bait",
  [TechnologyId.Refrigerator]: "Refrigerator",
  [TechnologyId.IceMine]: "Ice Mine",
  [TechnologyId.GroundGrenade]: "Ground Grenade",
  [TechnologyId.QuivernSaddle]: "Quivern Saddle",
  [TechnologyId.LeatherChairSet]: "Leather Chair Set",
  [TechnologyId.PIDFFlagSet]: "PIDF Flag Set",
  [TechnologyId.OreMiningSiteII]: "Ore Mining Site II",
  [TechnologyId.DoubleBarreledShotgun]: "Double-Barreled Shotgun",
  [TechnologyId.ShotgunShell]: "Shotgun Shell",
  [TechnologyId.SliderModule]: "Slider Module",
  [TechnologyId.RefinedMetalChest]: "Refined Metal Chest",
  [TechnologyId.AstegonSaddle]: "Astegon Saddle",
  [TechnologyId.ShroomerSaddle]: "Shroomer Saddle",
  [TechnologyId.ShroomerNoctSaddle]: "Shroomer Noct Saddle",
  [TechnologyId.MetalBat]: "Metal Bat",
  [TechnologyId.DoubleJumpBoots]: "Double Jump Boots",
  [TechnologyId.HeatResistantRefinedMetalArmor]: "Heat Resistant Refined Metal Armor",
  [TechnologyId.GigaGlider]: "Giga Glider",
  [TechnologyId.MountedMachineGun]: "Mounted Machine Gun",
  [TechnologyId.DarkGrenade]: "Dark Grenade",
  [TechnologyId.JormuntideSaddle]: "Jormuntide Saddle",
  [TechnologyId.GrizzboltSMinigun]: "Grizzbolt's Minigun",
  [TechnologyId.ChilletIgnisSaddle]: "Chillet Ignis Saddle",
  [TechnologyId.GuildChest]: "Guild Chest",
  [TechnologyId.SemiAutoRifle]: "Semi-Auto Rifle",
  [TechnologyId.ColdResistantRefinedMetalArmor]: "Cold Resistant Refined Metal Armor",
  [TechnologyId.ElectricKitchen]: "Electric Kitchen",
  [TechnologyId.AlphaWaveGenerator]: "Alpha Wave Generator",
  [TechnologyId.ElectricHeater]: "Electric Heater",
  [TechnologyId.XenogardSaddle]: "Xenogard Saddle",
  [TechnologyId.YakumoSaddle]: "Yakumo Saddle",
  [TechnologyId.MammorestCrystSaddle]: "Mammorest Cryst Saddle",
  [TechnologyId.CompoundBow]: "Compound Bow",
  [TechnologyId.ReinforcedArrow]: "Reinforced Arrow",
  [TechnologyId.ProductionAssemblyLineII]: "Production Assembly Line II",
  [TechnologyId.ElectricCooler]: "Electric Cooler",
  [TechnologyId.DragonGrenade]: "Dragon Grenade",
  [TechnologyId.WhalaskaSaddle]: "Whalaska Saddle",
  [TechnologyId.GhanglerIgnisSaddle]: "Ghangler Ignis Saddle",
  [TechnologyId.ReptyroSaddle]: "Reptyro Saddle",
  [TechnologyId.PumpActionShotgun]: "Pump-Action Shotgun",
  [TechnologyId.HyperShield]: "Hyper Shield",
  [TechnologyId.MediumPouch]: "Medium Pouch",
  [TechnologyId.HighQualityWoodenBoard]: "High Quality Wooden Board",
  [TechnologyId.ElectricMedicineWorkbench]: "Electric Medicine Workbench",
  [TechnologyId.SuzakuSaddle]: "Suzaku Saddle",
  [TechnologyId.ReptyroCrystSaddle]: "Reptyro Cryst Saddle",
  [TechnologyId.LoggingSiteII]: "Logging Site II",
  [TechnologyId.LegendarySphere]: "Legendary Sphere",
  [TechnologyId.ElectricFurnace]: "Electric Furnace",
  [TechnologyId.BioBattery]: "Bio Battery",
  [TechnologyId.Katana]: "Katana",
  [TechnologyId.PalMetalPickaxe]: "Pal Metal Pickaxe",
  [TechnologyId.PalMetalAxe]: "Pal Metal Axe",
  [TechnologyId.SuzakuAquaSaddle]: "Suzaku Aqua Saddle",
  [TechnologyId.BroncherryAquaSaddle]: "Broncherry Aqua Saddle",
  [TechnologyId.GlassStructureSet]: "Glass Structure Set",
  [TechnologyId.DecalGunSet]: "Decal Gun Set",
  [TechnologyId.AssaultRifle]: "Assault Rifle",
  [TechnologyId.AssaultRifleAmmo]: "Assault Rifle Ammo",
  [TechnologyId.AdvancedFishingRodPengullet]: "Advanced Fishing Rod (Pengullet)",
  [TechnologyId.DraftingTable]: "Drafting Table",
  [TechnologyId.QuivernBotanSaddle]: "Quivern Botan Saddle",
  [TechnologyId.RelaxaurusMissileLauncher]: "Relaxaurus' Missile Launcher",
  [TechnologyId.WumpoSaddle]: "Wumpo Saddle",
  [TechnologyId.SulfurQuarry]: "Sulfur Quarry",
  [TechnologyId.PalMetalArmor]: "Pal Metal Armor",
  [TechnologyId.PalMetalHelm]: "Pal Metal Helm",
  [TechnologyId.BetaWaveGenerator]: "Beta Wave Generator",
  [TechnologyId.LargeMountedLamp]: "Large Mounted Lamp",
  [TechnologyId.BlazamutSaddle]: "Blazamut Saddle",
  [TechnologyId.KingpacaCrystSaddle]: "Kingpaca Cryst Saddle",
  [TechnologyId.StreetLampSet]: "Street Lamp Set",
  [TechnologyId.AmusementFurnitureSet]: "Amusement Furniture Set",
  [TechnologyId.SemiAutoShotgun]: "Semi-Auto Shotgun",
  [TechnologyId.WeaponAssemblyLineII]: "Weapon Assembly Line II",
  [TechnologyId.VegetableCake]: "Vegetable Cake",
  [TechnologyId.GiantFeedBag]: "Giant Feed Bag",
  [TechnologyId.LargeCeilingLamp]: "Large Ceiling Lamp",
  [TechnologyId.HelzephyrLuxSaddle]: "Helzephyr Lux Saddle",
  [TechnologyId.ShadowbeakSaddle]: "Shadowbeak Saddle",
  [TechnologyId.EmergencyExitSignSet]: "Emergency Exit Sign Set",
  [TechnologyId.LargeIncubator]: "Large Incubator",
  [TechnologyId.HeatResistantPalMetalArmor]: "Heat Resistant Pal Metal Armor",
  [TechnologyId.SniperModuleII]: "Sniper Module II",
  [TechnologyId.ElectricPylon]: "Electric Pylon",
  [TechnologyId.RelaxaurusLuxSMissileLauncher]: "Relaxaurus Lux's Missile Launcher",
  [TechnologyId.DualithSaddle]: "Dualith Saddle",
  [TechnologyId.TetroiseSaddle]: "Tetroise Saddle",
  [TechnologyId.TrafficControlSet]: "Traffic Control Set",
  [TechnologyId.GrapplingGun4]: "GrapplingGun4",
  [TechnologyId.ItemRetrievalMachine]: "Item Retrieval Machine",
  [TechnologyId.LargeScaleStoneOven]: "Large-Scale Stone Oven",
  [TechnologyId.JapaneseStyleStructureSet]: "Japanese-Style Structure Set",
  [TechnologyId.FauxSnowyGreenerySet]: "Faux Snowy Greenery Set",
  [TechnologyId.RoadSignSet]: "Road Sign Set",
  [TechnologyId.BarricadeSet]: "Barricade Set",
  [TechnologyId.LargePowerGenerator]: "Large Power Generator",
  [TechnologyId.ColdResistantPalMetalArmor]: "Cold Resistant Pal Metal Armor",
  [TechnologyId.CrudeOilExtractor]: "Crude Oil Extractor",
  [TechnologyId.Plasteel]: "Plasteel",
  [TechnologyId.Computer]: "Computer",
  [TechnologyId.MountedMissileLauncher]: "Mounted Missile Launcher",
  [TechnologyId.PALGeneticResearchUnitFlagSet]: "PAL Genetic Research Unit Flag Set",
  [TechnologyId.HighPressureCrudeOilExtractor]: "High-Pressure Crude Oil Extractor",
  [TechnologyId.UltimateSphere]: "Ultimate Sphere",
  [TechnologyId.PlasteelArmor]: "Plasteel Armor",
  [TechnologyId.PlasteelHelmet]: "Plasteel Helmet",
  [TechnologyId.LaserRifle]: "Laser Rifle",
  [TechnologyId.EnergyCartridge]: "Energy Cartridge",
  [TechnologyId.ColdFoodBox]: "Cold Food Box",
  [TechnologyId.WumpoBotanSaddle]: "Wumpo Botan Saddle",
  [TechnologyId.GliderTera]: "Glider_Tera",
  [TechnologyId.Flamethrower]: "Flamethrower",
  [TechnologyId.FlamethrowerFuel]: "Flamethrower Fuel",
  [TechnologyId.AlluringBait]: "Alluring Bait",
  [TechnologyId.NyafiaSShotgun]: "Nyafia's Shotgun",
  [TechnologyId.PureQuartzQuarry]: "Pure Quartz Quarry",
  [TechnologyId.LargePouch]: "Large Pouch",
  [TechnologyId.HeatResistantPlasteelArmor]: "Heat Resistant Plasteel Armor",
  [TechnologyId.GrenadeLauncher]: "Grenade Launcher",
  [TechnologyId.GrenadeAmmo]: "Grenade Ammo",
  [TechnologyId.FragGrenadeMk2]: "Frag Grenade Mk2",
  [TechnologyId.SelyneSaddle]: "Selyne Saddle",
  [TechnologyId.LockpickingToolV3]: "Lockpicking Tool v3",
  [TechnologyId.BulldosuSaddle]: "Bulldosu Saddle",
  [TechnologyId.PlasmaMulticutter]: "Plasma Multicutter",
  [TechnologyId.ColdResistantPlasteelArmor]: "Cold Resistant Plasteel Armor",
  [TechnologyId.GatlingGun]: "Gatling Gun",
  [TechnologyId.GatlingGunAmmo]: "Gatling Gun Ammo",
  [TechnologyId.CryogenicCrusher]: "Cryogenic Crusher",
  [TechnologyId.ExtraWeaponHolster2]: "Extra Weapon Holster 2",
  [TechnologyId.GildaneSaddle]: "Gildane Saddle",
  [TechnologyId.CelesdirSaddle]: "Celesdir Saddle",
  [TechnologyId.LilySSpear]: "Lily's Spear",
  [TechnologyId.ShieldUltra]: "Shield_Ultra",
  [TechnologyId.LightweightPlasteelArmor]: "Lightweight Plasteel Armor",
  [TechnologyId.PolapupTerraSaddle]: "Polapup Terra Saddle",
  [TechnologyId.BlazamutRyuSaddle]: "Blazamut Ryu Saddle",
  [TechnologyId.JapaneseStyleFurnitureSet]: "Japanese-Style Furniture Set",
  [TechnologyId.MoonflowerFlagSet]: "Moonflower Flag Set",
  [TechnologyId.HomingSphereLauncher]: "Homing Sphere Launcher",
  [TechnologyId.GuidedMissileLauncher]: "Guided Missile Launcher",
  [TechnologyId.MissileAmmo]: "Missile Ammo",
  [TechnologyId.PalDisassemblyConveyor]: "Pal Disassembly Conveyor",
  [TechnologyId.PalPod]: "Pal Pod",
  [TechnologyId.ULTRAKILLCollabSet2]: "ULTRAKILL Collab Set 2",
  [TechnologyId.FauxCherryBlossomsSet]: "Faux Cherry Blossoms Set",
  [TechnologyId.AdvancedBow]: "Advanced Bow",
  [TechnologyId.AdvancedArrow]: "Advanced Arrow",
  [TechnologyId.GiantPouch]: "Giant Pouch",
  [TechnologyId.BeamSword]: "Beam Sword",
  [TechnologyId.StarryonSaddle]: "Starryon Saddle",
  [TechnologyId.FenglopeLuxSaddle]: "Fenglope Lux Saddle",
  [TechnologyId.KitsunSaddle]: "Kitsun Saddle",
  [TechnologyId.ExoticSphere]: "Exotic Sphere",
  [TechnologyId.AdvancedSphereAssemblyLine]: "Advanced Sphere Assembly Line",
  [TechnologyId.Hexolite]: "Hexolite",
  [TechnologyId.GiganticFurnace]: "Gigantic Furnace",
  [TechnologyId.MetalDetector]: "Metal Detector",
  [TechnologyId.SmokieSHarness]: "Smokie's Harness",
  [TechnologyId.AzurmaneSaddle]: "Azurmane Saddle",
  [TechnologyId.LargeScaleElectricEggIncubator]: "Large-Scale Electric Egg Incubator",
  [TechnologyId.AdvancedChest]: "Advanced Chest",
  [TechnologyId.LaserGatlingGun]: "Laser Gatling Gun",
  [TechnologyId.LaserGatlingCartridge]: "Laser Gatling Cartridge",
  [TechnologyId.HexoliteArmor]: "Hexolite Armor",
  [TechnologyId.ThermalCore]: "Thermal Core",
  [TechnologyId.JormuntideIgnisSaddle]: "Jormuntide Ignis Saddle",
  [TechnologyId.KitsunNoctSaddle]: "Kitsun Noct Saddle",
  [TechnologyId.AdvancedShield]: "Advanced Shield",
  [TechnologyId.HexoliteHelmet]: "Hexolite Helmet",
  [TechnologyId.ExtravagantVegetableCake]: "Extravagant Vegetable Cake",
  [TechnologyId.FeybreakFlagSet]: "Feybreak Flag Set",
  [TechnologyId.FalerisSaddle]: "Faleris Saddle",
  [TechnologyId.FalerisAquaSaddle]: "Faleris Aqua Saddle",
  [TechnologyId.SilvegisSaddle]: "Silvegis Saddle",
  [TechnologyId.PlasmaCannon]: "Plasma Cannon",
  [TechnologyId.PlasmaCartridge]: "Plasma Cartridge",
  [TechnologyId.AdvancedRecoveryMeds]: "Advanced Recovery Meds",
  [TechnologyId.RevivalPotion]: "Revival Potion",
  [TechnologyId.AdvancedMedicineWorkbench]: "Advanced Medicine Workbench",
  [TechnologyId.PaladiusSaddle]: "Paladius Saddle",
  [TechnologyId.NecromusSaddle]: "Necromus Saddle",
  [TechnologyId.DoubleAirDashBoots]: "Double Air Dash Boots",
  [TechnologyId.PowerfulFishingMagnet]: "Powerful Fishing Magnet",
  [TechnologyId.CoralumIngot]: "Coralum Ingot",
  [TechnologyId.AdvancedWorkshop]: "Advanced Workshop",
  [TechnologyId.FuturisticStructureSet]: "Futuristic Structure Set",
  [TechnologyId.HexoliteQuartzMine]: "Hexolite Quartz Mine",
  [TechnologyId.FrostallionSaddle]: "Frostallion Saddle",
  [TechnologyId.FrostallionNoctSaddle]: "Frostallion Noct Saddle",
  [TechnologyId.EnergyShotgun]: "Energy Shotgun",
  [TechnologyId.EnergyShotgunAmmo]: "Energy Shotgun Ammo",
  [TechnologyId.AdvancedWeaponAssemblyLine]: "Advanced Weapon Assembly Line",
  [TechnologyId.HeatResistantHexoliteArmor]: "Heat Resistant Hexolite Armor",
  [TechnologyId.MegaboostGun]: "Megaboost Gun",
  [TechnologyId.GrapplingGun5]: "GrapplingGun5",
  [TechnologyId.OverheatRifle]: "Overheat Rifle",
  [TechnologyId.OverheatRifleAmmo]: "Overheat Rifle Ammo",
  [TechnologyId.ColdResistantHexoliteArmor]: "Cold Resistant Hexolite Armor",
  [TechnologyId.JapaneseStyleHotSpring]: "Japanese-Style Hot Spring",
  [TechnologyId.UnivoltCrystSaddle]: "Univolt Cryst Saddle",
  [TechnologyId.NeptiliusSaddle]: "Neptilius Saddle",
  [TechnologyId.FrostallionStatue]: "Frostallion Statue",
  [TechnologyId.RocketLauncher]: "Rocket Launcher",
  [TechnologyId.RocketAmmo]: "Rocket Ammo",
  [TechnologyId.ChargeRifle]: "Charge Rifle",
  [TechnologyId.ChargeRifleAmmo]: "Charge Rifle Ammo",
  [TechnologyId.LightweightHexoliteArmor]: "Lightweight Hexolite Armor",
  [TechnologyId.SolmoraSaddle]: "Solmora Saddle",
  [TechnologyId.TripleAirDashBoots]: "Triple Air Dash Boots",
  [TechnologyId.AncientFurnace]: "Ancient Furnace",
  [TechnologyId.SoraliteIngot]: "Soralite Ingot",
  [TechnologyId.AquaticConstructionKit]: "Aquatic Construction Kit",
  [TechnologyId.SolmoraLuxSaddle]: "Solmora Lux Saddle",
  [TechnologyId.DynamoffSaddle]: "Dynamoff Saddle",
  [TechnologyId.XenolordSaddle]: "Xenolord Saddle",
  [TechnologyId.SolSphere]: "Sol Sphere",
  [TechnologyId.MechanicalBow]: "Mechanical Bow",
  [TechnologyId.MechanicalBowAmmo]: "Mechanical Bow Ammo",
  [TechnologyId.AICore]: "AI Core",
  [TechnologyId.AncientWorkbench]: "Ancient Workbench",
  [TechnologyId.AncientStructureSet]: "Ancient Structure Set",
  [TechnologyId.EnhancedLilySSpear]: "Enhanced Lily's Spear",
  [TechnologyId.CombatSMG]: "Combat SMG",
  [TechnologyId.CombatSMGAmmo]: "Combat SMG Ammo",
  [TechnologyId.AncientArmor]: "Ancient Armor",
  [TechnologyId.AncientHelm]: "Ancient Helm",
  [TechnologyId.EidrolonSaddle]: "Eidrolon Saddle",
  [TechnologyId.PrototypeShotgun]: "Prototype Shotgun",
  [TechnologyId.PrototypeShotgunAmmo]: "Prototype Shotgun Ammo",
  [TechnologyId.HomingModule]: "Homing Module",
  [TechnologyId.LargeFishingPond]: "Large Fishing Pond",
  [TechnologyId.DualithNoctSaddle]: "Dualith Noct Saddle",
  [TechnologyId.HeavyAssaultRifle]: "Heavy Assault Rifle",
  [TechnologyId.HeavyAssaultRifleAmmo]: "Heavy Assault Rifle Ammo",
  [TechnologyId.AncientKitchen]: "Ancient Kitchen",
  [TechnologyId.HartalisSaddle]: "Hartalis Saddle",
  [TechnologyId.TripleJumpBoots]: "Triple Jump Boots",
  [TechnologyId.MoldronCrystSaddle]: "Moldron Cryst Saddle",
  [TechnologyId.AncientShield]: "Ancient Shield",
  [TechnologyId.AncientMonitoringStand]: "Ancient Monitoring Stand",
  [TechnologyId.SkillfruitOrchard]: "Skillfruit Orchard",
  [TechnologyId.AzureCovenantFlagSet]: "Azure Covenant Flag Set",
  [TechnologyId.BeakonCrystSaddle]: "Beakon Cryst Saddle",
  [TechnologyId.WhalaskaIgnisSaddle]: "Whalaska Ignis Saddle",
  [TechnologyId.TacticalGrenadeLauncher]: "Tactical Grenade Launcher",
  [TechnologyId.TacticalGrenadeLauncherAmmo]: "Tactical Grenade Launcher Ammo",
  [TechnologyId.SoraliteQuarry]: "Soralite Quarry",
  [TechnologyId.RoujaySaddle]: "Roujay Saddle",
  [TechnologyId.OphydiaSaddle]: "Ophydia Saddle",
  [TechnologyId.LaserSword]: "Laser Sword",
  [TechnologyId.GoldCoinAssemblyLine]: "Gold Coin Assembly Line",
  [TechnologyId.AncientClinic]: "Ancient Clinic",
  [TechnologyId.AncientPalBed]: "Ancient Pal Bed",
  [TechnologyId.BastigorSHammer]: "Bastigor's Hammer",
  [TechnologyId.PaloxiteIngot]: "Paloxite Ingot",
  [TechnologyId.AncientSphere]: "Ancient Sphere",
  [TechnologyId.AncientRelicRecycler]: "Ancient Relic Recycler",
  [TechnologyId.SpecialCake]: "Special Cake",
  [TechnologyId.BeamScatter]: "Beam Scatter",
  [TechnologyId.BeamScatterAmmo]: "Beam Scatter Ammo",
  [TechnologyId.HeatResistantAncientArmor]: "Heat-Resistant Ancient Armor",
  [TechnologyId.AncientPowerGenerator]: "Ancient Power Generator",
  [TechnologyId.TetroisePrimoSaddle]: "Tetroise Primo Saddle",
  [TechnologyId.AncientHotSpring]: "Ancient Hot Spring",
  [TechnologyId.AncientHatchery]: "Ancient Hatchery",
  [TechnologyId.CorrosiveMistMask]: "Corrosive Mist Mask",
  [TechnologyId.ExplosionResistantUndershirt]: "Explosion-Resistant Undershirt",
  [TechnologyId.EidrolonIgnisSaddle]: "Eidrolon Ignis Saddle",
  [TechnologyId.DroneLauncher]: "Drone Launcher",
  [TechnologyId.ColdResistantAncientArmor]: "Cold-Resistant Ancient Armor",
  [TechnologyId.StarryonPrimoSaddle]: "Starryon Primo Saddle",
  [TechnologyId.ShaolongSaddle]: "Shaolong Saddle",
  [TechnologyId.PlasmaRifle]: "Plasma Rifle",
  [TechnologyId.PlasmaRifleAmmo]: "Plasma Rifle Ammo",
  [TechnologyId.AncientMaterialSynthesizer]: "Ancient Material Synthesizer",
  [TechnologyId.AncientFarm]: "Ancient Farm",
  [TechnologyId.CelesdirNoctSaddle]: "Celesdir Noct Saddle",
  [TechnologyId.LightweightAncientArmor]: "Lightweight Ancient Armor",
  [TechnologyId.NutrientTonic]: "Nutrient Tonic",
  [TechnologyId.AegidronSaddle]: "Aegidron Saddle",
  [TechnologyId.JetragonSMissileLauncher]: "Jetragon's Missile Launcher",
  [TechnologyId.JetragonStatue]: "Jetragon Statue",
  [TechnologyId.BeamLauncher]: "Beam Launcher",
  [TechnologyId.BeamLauncherAmmo]: "Beam Launcher Ammo",
  [TechnologyId.WingPack]: "Wing Pack",
  [TechnologyId.WingCell]: "Wing Cell",
};
